# constrain file of sword board
set_property PACKAGE_PIN M24 [get_ports SEGCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SEGCLK]
set_property PACKAGE_PIN P19 [get_ports SEGCLR]
set_property IOSTANDARD LVCMOS33 [get_ports SEGCLR]
set_property PACKAGE_PIN L24 [get_ports SEGDT]
set_property IOSTANDARD LVCMOS33 [get_ports SEGDT]
set_property PACKAGE_PIN R18 [get_ports SEGEN]
set_property IOSTANDARD LVCMOS33 [get_ports SEGEN]

# set_property PACKAGE_PIN M19 [get_ports PS2_Data]
# set_property IOSTANDARD LVCMOS33 [get_ports PS2_Data]
# set_property PULLUP true [get_ports PS2_Data]
# set_property PACKAGE_PIN N18 [get_ports PS2_clk]
# set_property IOSTANDARD LVCMOS33 [get_ports PS2_clk]
# set_property PULLUP true [get_ports PS2_clk]

set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVDS [get_ports clk]
set_property PACKAGE_PIN AD18 [get_ports sysclk_n]
set_property IOSTANDARD LVDS [get_ports sysclk_n]

set_property PACKAGE_PIN AF10 [get_ports rst]
set_property IOSTANDARD LVCMOS15 [get_ports rst]

# set_property PACKAGE_PIN AA10 [get_ports btn_clk]
# set_property IOSTANDARD LVCMOS15 [get_ports btn_clk]

# set_property IOSTANDARD LVCMOS15 [get_ports led_7]
# set_property PACKAGE_PIN W23 [get_ports led_7]
# set_property IOSTANDARD LVCMOS15 [get_ports led_6]
# set_property PACKAGE_PIN AB26 [get_ports led_6]

# use for  leds
set_property IOSTANDARD LVCMOS15 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds[0]}]
set_property PACKAGE_PIN W23     [get_ports {leds[7]}]
set_property PACKAGE_PIN AB26    [get_ports {leds[6]}]
set_property PACKAGE_PIN Y25     [get_ports {leds[5]}]
set_property PACKAGE_PIN AA23    [get_ports {leds[4]}]
set_property PACKAGE_PIN Y23     [get_ports {leds[3]}]
set_property PACKAGE_PIN Y22     [get_ports {leds[2]}]
set_property PACKAGE_PIN AE21    [get_ports {leds[1]}]
set_property PACKAGE_PIN AF24    [get_ports {leds[0]}]

# use for keyboard
set_property PACKAGE_PIN M19 [get_ports PS2_Data]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_Data]
set_property PULLUP true [get_ports PS2_Data]
set_property PACKAGE_PIN N18 [get_ports PS2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_clk]
set_property PULLUP true [get_ports PS2_clk]


# use for switch
set_property PACKAGE_PIN AA10 [get_ports {swt[0]}]
set_property PACKAGE_PIN AB10 [get_ports {swt[1]}]
set_property PACKAGE_PIN AA13 [get_ports {swt[2]}]
set_property PACKAGE_PIN AA12 [get_ports {swt[3]}]
set_property PACKAGE_PIN Y13 [get_ports {swt[4]}]
set_property PACKAGE_PIN Y12 [get_ports {swt[5]}]
set_property PACKAGE_PIN AD11 [get_ports {swt[6]}]
set_property PACKAGE_PIN AD10 [get_ports {swt[7]}]
# set_property PACKAGE_PIN AE10 [get_ports {swt[8]}]
# set_property PACKAGE_PIN AE12 [get_ports {swt[9]}]
# set_property PACKAGE_PIN AF12 [get_ports {swt[10]}]
# set_property PACKAGE_PIN AE8 [get_ports {swt[11]}]
# set_property PACKAGE_PIN AF8 [get_ports {swt[12]}]
# set_property PACKAGE_PIN AE13 [get_ports {swt[13]}]
# set_property PACKAGE_PIN AF13 [get_ports {swt[14]}]
# set_property PACKAGE_PIN AF10 [get_ports {swt[15]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[15]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[14]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[13]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[12]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[11]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[10]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[9]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {swt[8]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {swt[0]}]
