NAME     := am
# $(error $(AM_SRCS))
SRCS      = $(addprefix src/, $(AM_SRCS))
# $(error $(SRCS))
INC_PATH += $(AM_HOME)/am/src

include $(AM_HOME)/Makefile

# AM_SRCS is assigned in include 's include (native.mk)
# $(error $(AM_SRCS))
