// Generated by CIRCT firtool-1.43.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module D_Cache(	// <stdin>:3113:10
  input         clock,	// <stdin>:3114:11
                reset,	// <stdin>:3115:11
                from_LSU_valid,	// src/main/scala/rv32e/cache/dcache.scala:15:22
  input  [31:0] from_LSU_bits_addr,	// src/main/scala/rv32e/cache/dcache.scala:15:22
                from_LSU_bits_wdata,	// src/main/scala/rv32e/cache/dcache.scala:15:22
  input         from_LSU_bits_is_write,	// src/main/scala/rv32e/cache/dcache.scala:15:22
  input  [31:0] from_LSU_bits_wmask,	// src/main/scala/rv32e/cache/dcache.scala:15:22
  input         to_sram_ar_ready,	// src/main/scala/rv32e/cache/dcache.scala:17:22
                to_sram_r_valid,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  input  [31:0] to_sram_r_bits_data,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  input         to_sram_r_bits_last,	// src/main/scala/rv32e/cache/dcache.scala:17:22
                to_sram_aw_ready,	// src/main/scala/rv32e/cache/dcache.scala:17:22
                to_sram_w_ready,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output        from_LSU_ready,	// src/main/scala/rv32e/cache/dcache.scala:15:22
                to_LSU_valid,	// src/main/scala/rv32e/cache/dcache.scala:16:22
  output [31:0] to_LSU_bits_data,	// src/main/scala/rv32e/cache/dcache.scala:16:22
  output        to_LSU_bits_bresp,	// src/main/scala/rv32e/cache/dcache.scala:16:22
                to_sram_ar_valid,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output [31:0] to_sram_ar_bits_addr,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output [7:0]  to_sram_ar_bits_len,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output        to_sram_r_ready,	// src/main/scala/rv32e/cache/dcache.scala:17:22
                to_sram_aw_valid,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output [31:0] to_sram_aw_bits_addr,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output [7:0]  to_sram_aw_bits_len,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output        to_sram_w_valid,	// src/main/scala/rv32e/cache/dcache.scala:17:22
  output [31:0] to_sram_w_bits_data	// src/main/scala/rv32e/cache/dcache.scala:17:22
);

  wire [31:0]       _dataArray_ext_R0_data;	// src/main/scala/rv32e/cache/dcache.scala:30:33
  reg               replace_set;	// src/main/scala/rv32e/cache/dcache.scala:19:30
  reg               random_num;	// src/main/scala/rv32e/cache/dcache.scala:26:29
  reg  [23:0]       tagArray_0_0;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_1;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_2;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_3;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_4;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_5;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_6;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_7;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_8;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_9;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_10;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_11;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_12;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_13;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_14;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_0_15;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_0;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_1;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_2;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_3;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_4;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_5;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_6;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_7;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_8;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_9;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_10;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_11;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_12;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_13;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_14;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg  [23:0]       tagArray_1_15;	// src/main/scala/rv32e/cache/dcache.scala:31:29
  reg               validArray_0_0;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_1;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_2;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_3;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_4;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_5;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_6;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_7;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_8;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_9;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_10;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_11;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_12;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_13;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_14;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_0_15;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_0;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_1;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_2;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_3;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_4;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_5;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_6;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_7;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_8;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_9;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_10;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_11;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_12;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_13;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_14;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               validArray_1_15;	// src/main/scala/rv32e/cache/dcache.scala:32:29
  reg               dirtyArray_0_0;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_1;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_2;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_3;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_4;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_5;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_6;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_7;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_8;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_9;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_10;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_11;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_12;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_13;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_14;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_0_15;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_0;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_1;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_2;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_3;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_4;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_5;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_6;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_7;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_8;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_9;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_10;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_11;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_12;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_13;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_14;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  reg               dirtyArray_1_15;	// src/main/scala/rv32e/cache/dcache.scala:33:29
  wire [15:0][23:0] _GEN =
    {{tagArray_0_15},
     {tagArray_0_14},
     {tagArray_0_13},
     {tagArray_0_12},
     {tagArray_0_11},
     {tagArray_0_10},
     {tagArray_0_9},
     {tagArray_0_8},
     {tagArray_0_7},
     {tagArray_0_6},
     {tagArray_0_5},
     {tagArray_0_4},
     {tagArray_0_3},
     {tagArray_0_2},
     {tagArray_0_1},
     {tagArray_0_0}};	// src/main/scala/rv32e/cache/dcache.scala:31:29, :36:14
  wire [15:0]       _GEN_0 =
    {{validArray_0_15},
     {validArray_0_14},
     {validArray_0_13},
     {validArray_0_12},
     {validArray_0_11},
     {validArray_0_10},
     {validArray_0_9},
     {validArray_0_8},
     {validArray_0_7},
     {validArray_0_6},
     {validArray_0_5},
     {validArray_0_4},
     {validArray_0_3},
     {validArray_0_2},
     {validArray_0_1},
     {validArray_0_0}};	// src/main/scala/rv32e/cache/dcache.scala:32:29, :36:44
  wire [15:0][23:0] _GEN_1 =
    {{tagArray_1_15},
     {tagArray_1_14},
     {tagArray_1_13},
     {tagArray_1_12},
     {tagArray_1_11},
     {tagArray_1_10},
     {tagArray_1_9},
     {tagArray_1_8},
     {tagArray_1_7},
     {tagArray_1_6},
     {tagArray_1_5},
     {tagArray_1_4},
     {tagArray_1_3},
     {tagArray_1_2},
     {tagArray_1_1},
     {tagArray_1_0}};	// src/main/scala/rv32e/cache/dcache.scala:31:29, :36:14
  wire              SetId = from_LSU_bits_addr[31:8] == _GEN_1[from_LSU_bits_addr[7:4]];	// src/main/scala/rv32e/cache/dcache.scala:22:41, :23:41, :36:14
  wire [15:0]       _GEN_2 =
    {{validArray_1_15},
     {validArray_1_14},
     {validArray_1_13},
     {validArray_1_12},
     {validArray_1_11},
     {validArray_1_10},
     {validArray_1_9},
     {validArray_1_8},
     {validArray_1_7},
     {validArray_1_6},
     {validArray_1_5},
     {validArray_1_4},
     {validArray_1_3},
     {validArray_1_2},
     {validArray_1_1},
     {validArray_1_0}};	// src/main/scala/rv32e/cache/dcache.scala:32:29, :36:44
  wire              hit =
    from_LSU_bits_addr[31:8] == _GEN[from_LSU_bits_addr[7:4]]
    & _GEN_0[from_LSU_bits_addr[7:4]] | SetId & _GEN_2[from_LSU_bits_addr[7:4]];	// src/main/scala/rv32e/cache/dcache.scala:22:41, :23:41, :36:{14,44}, :38:33
  wire [6:0]        hitCacheAddr = {SetId, from_LSU_bits_addr[7:2]};	// src/main/scala/rv32e/cache/dcache.scala:36:14, :45:27
  reg  [1:0]        off;	// src/main/scala/rv32e/cache/dcache.scala:49:24
  reg  [3:0]        state_dcache;	// src/main/scala/rv32e/cache/dcache.scala:55:31
  wire              _from_LSU_ready_output = state_dcache == 4'h0;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27
  wire              _GEN_3 = state_dcache == 4'h1;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :60:40
  wire              _GEN_4 = state_dcache == 4'h2;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :60:40
  wire              _to_sram_aw_valid_output = state_dcache == 4'h4;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :76:32
  wire              _to_sram_w_valid_output = state_dcache == 4'h5;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :79:32
  wire              _to_sram_ar_valid_output = state_dcache == 4'h7;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :76:32
  wire              _to_sram_r_ready_output = state_dcache == 4'h8;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :92:32
  wire              _GEN_5 = _to_sram_r_ready_output & to_sram_r_valid;	// src/main/scala/rv32e/cache/dcache.scala:49:24, :56:27, :98:{26,32}
  wire [6:0]        replaceCacheAddr = {replace_set, from_LSU_bits_addr[7:4], off};	// src/main/scala/rv32e/cache/dcache.scala:19:30, :22:41, :49:24, :107:31
  wire [94:0]       _GEN_6 =
    {63'h0, from_LSU_bits_wdata} << {90'h0, from_LSU_bits_addr[1:0], 3'h0};	// src/main/scala/rv32e/cache/dcache.scala:20:41, :126:28, :139:{93,106}
  wire [15:0][23:0] _GEN_7 = replace_set ? _GEN_1 : _GEN;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :36:14, :145:33
  always @(posedge clock) begin	// <stdin>:3114:11
    if (reset) begin	// <stdin>:3114:11
      replace_set <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:19:30
      random_num <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:26:29
      tagArray_0_0 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_1 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_2 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_3 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_4 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_5 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_6 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_7 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_8 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_9 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_10 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_11 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_12 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_13 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_14 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_0_15 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_0 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_1 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_2 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_3 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_4 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_5 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_6 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_7 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_8 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_9 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_10 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_11 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_12 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_13 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_14 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      tagArray_1_15 <= 24'h0;	// src/main/scala/rv32e/cache/dcache.scala:31:{29,63}
      validArray_0_0 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_1 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_2 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_3 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_4 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_5 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_6 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_7 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_8 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_9 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_10 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_11 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_12 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_13 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_14 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_0_15 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_0 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_1 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_2 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_3 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_4 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_5 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_6 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_7 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_8 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_9 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_10 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_11 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_12 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_13 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_14 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      validArray_1_15 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
      dirtyArray_0_0 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_1 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_2 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_3 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_4 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_5 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_6 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_7 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_8 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_9 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_10 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_11 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_12 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_13 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_14 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_0_15 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_0 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_1 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_2 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_3 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_4 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_5 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_6 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_7 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_8 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_9 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_10 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_11 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_12 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_13 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_14 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      dirtyArray_1_15 <= 1'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
      off <= 2'h0;	// src/main/scala/rv32e/cache/dcache.scala:49:24
      state_dcache <= 4'h0;	// src/main/scala/rv32e/cache/dcache.scala:55:31
    end
    else begin	// <stdin>:3114:11
      automatic logic             _GEN_8 = _from_LSU_ready_output & from_LSU_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rv32e/cache/dcache.scala:56:27
      automatic logic [3:0]       _GEN_9 = from_LSU_bits_is_write ? 4'h2 : 4'h1;	// src/main/scala/rv32e/cache/dcache.scala:60:40
      automatic logic             _GEN_10 = from_LSU_bits_addr[7:4] == 4'h0;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :55:31, :116:50
      automatic logic             _GEN_11;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_12 = from_LSU_bits_addr[7:4] == 4'h1;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :60:40, :116:50
      automatic logic             _GEN_13;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_14 = from_LSU_bits_addr[7:4] == 4'h2;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :60:40, :116:50
      automatic logic             _GEN_15;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_16 = from_LSU_bits_addr[7:4] == 4'h3;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :63:34, :116:50
      automatic logic             _GEN_17;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_18 = from_LSU_bits_addr[7:4] == 4'h4;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :76:32, :116:50
      automatic logic             _GEN_19;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_20 = from_LSU_bits_addr[7:4] == 4'h5;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :79:32, :116:50
      automatic logic             _GEN_21;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_22 = from_LSU_bits_addr[7:4] == 4'h6;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :83:32, :116:50
      automatic logic             _GEN_23;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_24 = from_LSU_bits_addr[7:4] == 4'h7;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :76:32, :116:50
      automatic logic             _GEN_25;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_26 = from_LSU_bits_addr[7:4] == 4'h8;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :92:32, :116:50
      automatic logic             _GEN_27;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_28 = from_LSU_bits_addr[7:4] == 4'h9;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :97:32, :116:50
      automatic logic             _GEN_29;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_30 = from_LSU_bits_addr[7:4] == 4'hA;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :116:50
      automatic logic             _GEN_31;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_32 = from_LSU_bits_addr[7:4] == 4'hB;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :116:50
      automatic logic             _GEN_33;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_34 = from_LSU_bits_addr[7:4] == 4'hC;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :116:50
      automatic logic             _GEN_35;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_36 = from_LSU_bits_addr[7:4] == 4'hD;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :116:50
      automatic logic             _GEN_37;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_38 = from_LSU_bits_addr[7:4] == 4'hE;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :116:50
      automatic logic             _GEN_39;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_40;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_41;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_42;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_43;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_44;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_45;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_46;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_47;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_48;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_49;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_50;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_51;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_52;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_53;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_54;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_55;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic             _GEN_56;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      automatic logic [15:0]      _GEN_57;	// src/main/scala/rv32e/cache/dcache.scala:76:32
      automatic logic [15:0][3:0] _GEN_58;	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :58:34, :70:26, :73:26, :76:26, :79:26, :83:26, :88:26, :92:26, :97:26, :103:26
      _GEN_11 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_10;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_13 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_12;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_15 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_14;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_17 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_16;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_19 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_18;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_21 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_20;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_23 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_22;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_25 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_24;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_27 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_26;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_29 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_28;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_31 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_30;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_33 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_32;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_35 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_34;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_37 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_36;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_39 = _GEN_5 & to_sram_r_bits_last & ~replace_set & _GEN_38;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_40 =
        _GEN_5 & to_sram_r_bits_last & ~replace_set & (&(from_LSU_bits_addr[7:4]));	// src/main/scala/rv32e/cache/dcache.scala:19:30, :22:41, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_41 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_10;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_42 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_12;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_43 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_14;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_44 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_16;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_45 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_18;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_46 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_20;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_47 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_22;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_48 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_24;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_49 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_26;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_50 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_28;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_51 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_30;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_52 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_32;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_53 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_34;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_54 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_36;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_55 = _GEN_5 & to_sram_r_bits_last & replace_set & _GEN_38;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      _GEN_56 = _GEN_5 & to_sram_r_bits_last & replace_set & (&(from_LSU_bits_addr[7:4]));	// src/main/scala/rv32e/cache/dcache.scala:19:30, :22:41, :32:29, :49:24, :56:27, :98:{26,32}, :113:59, :115:35, :116:50
      if (~(_from_LSU_ready_output & _GEN_8) | hit) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rv32e/cache/dcache.scala:19:30, :38:33, :56:27, :58:34, :59:28
      end
      else	// src/main/scala/rv32e/cache/dcache.scala:19:30, :56:27, :58:34, :59:28
        replace_set <= random_num;	// src/main/scala/rv32e/cache/dcache.scala:19:30, :26:29
      random_num <= random_num - 1'h1;	// src/main/scala/rv32e/cache/dcache.scala:26:29, :27:33
      if (_GEN_11)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_0 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_13)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_1 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_15)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_2 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_17)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_3 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_19)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_4 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_21)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_5 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_23)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_6 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_25)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_7 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_27)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_8 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_29)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_9 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_31)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_10 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_33)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_11 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_35)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_12 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_37)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_13 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_39)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_14 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_40)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_0_15 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_41)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_0 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_42)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_1 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_43)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_2 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_44)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_3 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_45)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_4 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_46)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_5 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_47)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_6 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_48)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_7 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_49)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_8 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_50)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_9 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_51)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_10 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_52)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_11 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_53)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_12 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_54)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_13 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_55)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_14 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      if (_GEN_56)	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
        tagArray_1_15 <= from_LSU_bits_addr[31:8];	// src/main/scala/rv32e/cache/dcache.scala:23:41, :31:29
      validArray_0_0 <= _GEN_11 | validArray_0_0;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_1 <= _GEN_13 | validArray_0_1;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_2 <= _GEN_15 | validArray_0_2;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_3 <= _GEN_17 | validArray_0_3;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_4 <= _GEN_19 | validArray_0_4;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_5 <= _GEN_21 | validArray_0_5;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_6 <= _GEN_23 | validArray_0_6;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_7 <= _GEN_25 | validArray_0_7;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_8 <= _GEN_27 | validArray_0_8;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_9 <= _GEN_29 | validArray_0_9;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_10 <= _GEN_31 | validArray_0_10;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_11 <= _GEN_33 | validArray_0_11;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_12 <= _GEN_35 | validArray_0_12;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_13 <= _GEN_37 | validArray_0_13;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_14 <= _GEN_39 | validArray_0_14;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_0_15 <= _GEN_40 | validArray_0_15;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_0 <= _GEN_41 | validArray_1_0;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_1 <= _GEN_42 | validArray_1_1;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_2 <= _GEN_43 | validArray_1_2;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_3 <= _GEN_44 | validArray_1_3;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_4 <= _GEN_45 | validArray_1_4;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_5 <= _GEN_46 | validArray_1_5;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_6 <= _GEN_47 | validArray_1_6;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_7 <= _GEN_48 | validArray_1_7;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_8 <= _GEN_49 | validArray_1_8;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_9 <= _GEN_50 | validArray_1_9;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_10 <= _GEN_51 | validArray_1_10;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_11 <= _GEN_52 | validArray_1_11;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_12 <= _GEN_53 | validArray_1_12;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_13 <= _GEN_54 | validArray_1_13;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_14 <= _GEN_55 | validArray_1_14;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      validArray_1_15 <= _GEN_56 | validArray_1_15;	// src/main/scala/rv32e/cache/dcache.scala:32:29, :113:59, :115:35, :116:50
      dirtyArray_0_0 <= _GEN_4 & ~SetId & _GEN_10 | dirtyArray_0_0;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_1 <= _GEN_4 & ~SetId & _GEN_12 | dirtyArray_0_1;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_2 <= _GEN_4 & ~SetId & _GEN_14 | dirtyArray_0_2;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_3 <= _GEN_4 & ~SetId & _GEN_16 | dirtyArray_0_3;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_4 <= _GEN_4 & ~SetId & _GEN_18 | dirtyArray_0_4;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_5 <= _GEN_4 & ~SetId & _GEN_20 | dirtyArray_0_5;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_6 <= _GEN_4 & ~SetId & _GEN_22 | dirtyArray_0_6;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_7 <= _GEN_4 & ~SetId & _GEN_24 | dirtyArray_0_7;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_8 <= _GEN_4 & ~SetId & _GEN_26 | dirtyArray_0_8;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_9 <= _GEN_4 & ~SetId & _GEN_28 | dirtyArray_0_9;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_10 <= _GEN_4 & ~SetId & _GEN_30 | dirtyArray_0_10;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_11 <= _GEN_4 & ~SetId & _GEN_32 | dirtyArray_0_11;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_12 <= _GEN_4 & ~SetId & _GEN_34 | dirtyArray_0_12;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_13 <= _GEN_4 & ~SetId & _GEN_36 | dirtyArray_0_13;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_14 <= _GEN_4 & ~SetId & _GEN_38 | dirtyArray_0_14;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_0_15 <= _GEN_4 & ~SetId & (&(from_LSU_bits_addr[7:4])) | dirtyArray_0_15;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_0 <= _GEN_4 & SetId & _GEN_10 | dirtyArray_1_0;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_1 <= _GEN_4 & SetId & _GEN_12 | dirtyArray_1_1;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_2 <= _GEN_4 & SetId & _GEN_14 | dirtyArray_1_2;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_3 <= _GEN_4 & SetId & _GEN_16 | dirtyArray_1_3;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_4 <= _GEN_4 & SetId & _GEN_18 | dirtyArray_1_4;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_5 <= _GEN_4 & SetId & _GEN_20 | dirtyArray_1_5;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_6 <= _GEN_4 & SetId & _GEN_22 | dirtyArray_1_6;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_7 <= _GEN_4 & SetId & _GEN_24 | dirtyArray_1_7;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_8 <= _GEN_4 & SetId & _GEN_26 | dirtyArray_1_8;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_9 <= _GEN_4 & SetId & _GEN_28 | dirtyArray_1_9;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_10 <= _GEN_4 & SetId & _GEN_30 | dirtyArray_1_10;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_11 <= _GEN_4 & SetId & _GEN_32 | dirtyArray_1_11;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_12 <= _GEN_4 & SetId & _GEN_34 | dirtyArray_1_12;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_13 <= _GEN_4 & SetId & _GEN_36 | dirtyArray_1_13;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_14 <= _GEN_4 & SetId & _GEN_38 | dirtyArray_1_14;	// src/main/scala/rv32e/cache/dcache.scala:33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      dirtyArray_1_15 <= _GEN_4 & SetId & (&(from_LSU_bits_addr[7:4])) | dirtyArray_1_15;	// src/main/scala/rv32e/cache/dcache.scala:22:41, :33:29, :36:14, :56:27, :116:50, :127:39, :129:46
      if (~(_from_LSU_ready_output | _GEN_3 | _GEN_4 | state_dcache == 4'h3)) begin	// src/main/scala/rv32e/cache/dcache.scala:49:24, :55:31, :56:27, :63:34
        if (_to_sram_aw_valid_output)	// src/main/scala/rv32e/cache/dcache.scala:56:27
          off <= 2'h0;	// src/main/scala/rv32e/cache/dcache.scala:49:24
        else begin	// src/main/scala/rv32e/cache/dcache.scala:56:27
          automatic logic [1:0] _GEN_59;	// src/main/scala/rv32e/cache/dcache.scala:84:52
          _GEN_59 = off + 2'h1;	// src/main/scala/rv32e/cache/dcache.scala:49:24, :84:52
          if (_to_sram_w_valid_output) begin	// src/main/scala/rv32e/cache/dcache.scala:56:27
            if (to_sram_w_ready & _to_sram_w_valid_output)	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rv32e/cache/dcache.scala:56:27
              off <= _GEN_59;	// src/main/scala/rv32e/cache/dcache.scala:49:24, :84:52
          end
          else if (state_dcache != 4'h6) begin	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :83:32
            if (_to_sram_ar_valid_output)	// src/main/scala/rv32e/cache/dcache.scala:56:27
              off <= 2'h0;	// src/main/scala/rv32e/cache/dcache.scala:49:24
            else if (_GEN_5)	// src/main/scala/rv32e/cache/dcache.scala:49:24, :56:27, :98:{26,32}
              off <= _GEN_59;	// src/main/scala/rv32e/cache/dcache.scala:49:24, :84:52
          end
        end
      end
      _GEN_57 =
        replace_set
          ? {{dirtyArray_1_15},
             {dirtyArray_1_14},
             {dirtyArray_1_13},
             {dirtyArray_1_12},
             {dirtyArray_1_11},
             {dirtyArray_1_10},
             {dirtyArray_1_9},
             {dirtyArray_1_8},
             {dirtyArray_1_7},
             {dirtyArray_1_6},
             {dirtyArray_1_5},
             {dirtyArray_1_4},
             {dirtyArray_1_3},
             {dirtyArray_1_2},
             {dirtyArray_1_1},
             {dirtyArray_1_0}}
          : {{dirtyArray_0_15},
             {dirtyArray_0_14},
             {dirtyArray_0_13},
             {dirtyArray_0_12},
             {dirtyArray_0_11},
             {dirtyArray_0_10},
             {dirtyArray_0_9},
             {dirtyArray_0_8},
             {dirtyArray_0_7},
             {dirtyArray_0_6},
             {dirtyArray_0_5},
             {dirtyArray_0_4},
             {dirtyArray_0_3},
             {dirtyArray_0_2},
             {dirtyArray_0_1},
             {dirtyArray_0_0}};	// src/main/scala/rv32e/cache/dcache.scala:19:30, :33:29, :76:32
      _GEN_58 =
        {{state_dcache},
         {state_dcache},
         {state_dcache},
         {state_dcache},
         {state_dcache},
         {state_dcache},
         {_GEN_9},
         {{3'h4, to_sram_r_bits_last}},
         {to_sram_ar_ready & _to_sram_ar_valid_output ? 4'h8 : 4'h7},
         {4'h7},
         {(&off) ? 4'h6 : 4'h5},
         {{3'h2, to_sram_aw_ready & _to_sram_aw_valid_output}},
         {_GEN_57[from_LSU_bits_addr[7:4]] ? 4'h4 : 4'h7},
         {4'h0},
         {4'h0},
         {_GEN_8 ? (hit ? _GEN_9 : 4'h3) : 4'h0}};	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rv32e/cache/dcache.scala:22:41, :38:33, :49:24, :55:31, :56:27, :58:34, :59:28, :60:{34,40}, :63:34, :66:30, :70:26, :73:26, :76:{26,32}, :79:{26,32}, :83:{26,32,38}, :88:26, :92:{26,32}, :97:{26,32}, :103:26
      state_dcache <= _GEN_58[state_dcache];	// src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :58:34, :70:26, :73:26, :76:26, :79:26, :83:26, :88:26, :92:26, :97:26, :103:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:3113:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:3113:10
      `FIRRTL_BEFORE_INITIAL	// <stdin>:3113:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:3113:10
      automatic logic [31:0] _RANDOM[0:26];	// <stdin>:3113:10
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:3113:10
        `INIT_RANDOM_PROLOG_	// <stdin>:3113:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:3113:10
        for (logic [4:0] i = 5'h0; i < 5'h1B; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// <stdin>:3113:10
        end	// <stdin>:3113:10
        replace_set = _RANDOM[5'h0][0];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:19:30
        random_num = _RANDOM[5'h0][1];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:19:30, :26:29
        tagArray_0_0 = _RANDOM[5'h0][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:19:30, :31:29
        tagArray_0_1 = {_RANDOM[5'h0][31:26], _RANDOM[5'h1][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:19:30, :31:29
        tagArray_0_2 = {_RANDOM[5'h1][31:18], _RANDOM[5'h2][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_3 = {_RANDOM[5'h2][31:10], _RANDOM[5'h3][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_4 = _RANDOM[5'h3][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_5 = {_RANDOM[5'h3][31:26], _RANDOM[5'h4][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_6 = {_RANDOM[5'h4][31:18], _RANDOM[5'h5][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_7 = {_RANDOM[5'h5][31:10], _RANDOM[5'h6][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_8 = _RANDOM[5'h6][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_9 = {_RANDOM[5'h6][31:26], _RANDOM[5'h7][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_10 = {_RANDOM[5'h7][31:18], _RANDOM[5'h8][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_11 = {_RANDOM[5'h8][31:10], _RANDOM[5'h9][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_12 = _RANDOM[5'h9][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_13 = {_RANDOM[5'h9][31:26], _RANDOM[5'hA][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_14 = {_RANDOM[5'hA][31:18], _RANDOM[5'hB][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_0_15 = {_RANDOM[5'hB][31:10], _RANDOM[5'hC][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_0 = _RANDOM[5'hC][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_1 = {_RANDOM[5'hC][31:26], _RANDOM[5'hD][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_2 = {_RANDOM[5'hD][31:18], _RANDOM[5'hE][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_3 = {_RANDOM[5'hE][31:10], _RANDOM[5'hF][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_4 = _RANDOM[5'hF][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_5 = {_RANDOM[5'hF][31:26], _RANDOM[5'h10][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_6 = {_RANDOM[5'h10][31:18], _RANDOM[5'h11][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_7 = {_RANDOM[5'h11][31:10], _RANDOM[5'h12][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_8 = _RANDOM[5'h12][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_9 = {_RANDOM[5'h12][31:26], _RANDOM[5'h13][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_10 = {_RANDOM[5'h13][31:18], _RANDOM[5'h14][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_11 = {_RANDOM[5'h14][31:10], _RANDOM[5'h15][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_12 = _RANDOM[5'h15][25:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_13 = {_RANDOM[5'h15][31:26], _RANDOM[5'h16][17:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_14 = {_RANDOM[5'h16][31:18], _RANDOM[5'h17][9:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        tagArray_1_15 = {_RANDOM[5'h17][31:10], _RANDOM[5'h18][1:0]};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29
        validArray_0_0 = _RANDOM[5'h18][2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_1 = _RANDOM[5'h18][3];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_2 = _RANDOM[5'h18][4];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_3 = _RANDOM[5'h18][5];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_4 = _RANDOM[5'h18][6];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_5 = _RANDOM[5'h18][7];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_6 = _RANDOM[5'h18][8];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_7 = _RANDOM[5'h18][9];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_8 = _RANDOM[5'h18][10];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_9 = _RANDOM[5'h18][11];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_10 = _RANDOM[5'h18][12];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_11 = _RANDOM[5'h18][13];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_12 = _RANDOM[5'h18][14];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_13 = _RANDOM[5'h18][15];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_14 = _RANDOM[5'h18][16];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_0_15 = _RANDOM[5'h18][17];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_0 = _RANDOM[5'h18][18];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_1 = _RANDOM[5'h18][19];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_2 = _RANDOM[5'h18][20];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_3 = _RANDOM[5'h18][21];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_4 = _RANDOM[5'h18][22];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_5 = _RANDOM[5'h18][23];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_6 = _RANDOM[5'h18][24];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_7 = _RANDOM[5'h18][25];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_8 = _RANDOM[5'h18][26];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_9 = _RANDOM[5'h18][27];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_10 = _RANDOM[5'h18][28];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_11 = _RANDOM[5'h18][29];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_12 = _RANDOM[5'h18][30];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_13 = _RANDOM[5'h18][31];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:31:29, :32:29
        validArray_1_14 = _RANDOM[5'h19][0];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
        validArray_1_15 = _RANDOM[5'h19][1];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29
        dirtyArray_0_0 = _RANDOM[5'h19][2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_1 = _RANDOM[5'h19][3];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_2 = _RANDOM[5'h19][4];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_3 = _RANDOM[5'h19][5];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_4 = _RANDOM[5'h19][6];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_5 = _RANDOM[5'h19][7];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_6 = _RANDOM[5'h19][8];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_7 = _RANDOM[5'h19][9];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_8 = _RANDOM[5'h19][10];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_9 = _RANDOM[5'h19][11];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_10 = _RANDOM[5'h19][12];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_11 = _RANDOM[5'h19][13];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_12 = _RANDOM[5'h19][14];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_13 = _RANDOM[5'h19][15];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_14 = _RANDOM[5'h19][16];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_0_15 = _RANDOM[5'h19][17];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_0 = _RANDOM[5'h19][18];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_1 = _RANDOM[5'h19][19];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_2 = _RANDOM[5'h19][20];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_3 = _RANDOM[5'h19][21];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_4 = _RANDOM[5'h19][22];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_5 = _RANDOM[5'h19][23];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_6 = _RANDOM[5'h19][24];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_7 = _RANDOM[5'h19][25];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_8 = _RANDOM[5'h19][26];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_9 = _RANDOM[5'h19][27];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_10 = _RANDOM[5'h19][28];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_11 = _RANDOM[5'h19][29];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_12 = _RANDOM[5'h19][30];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_13 = _RANDOM[5'h19][31];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:32:29, :33:29
        dirtyArray_1_14 = _RANDOM[5'h1A][0];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
        dirtyArray_1_15 = _RANDOM[5'h1A][1];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29
        off = _RANDOM[5'h1A][3:2];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29, :49:24
        state_dcache = _RANDOM[5'h1A][7:4];	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:33:29, :55:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:3113:10
      `FIRRTL_AFTER_INITIAL	// <stdin>:3113:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  dataArray_combMem_0 dataArray_ext (	// src/main/scala/rv32e/cache/dcache.scala:30:33
    .R0_addr (hitCacheAddr),	// src/main/scala/rv32e/cache/dcache.scala:45:27
    .R0_en   (1'h1),	// <stdin>:3113:10
    .R0_clk  (clock),
    .R1_addr (replaceCacheAddr),	// src/main/scala/rv32e/cache/dcache.scala:107:31
    .R1_en   (1'h1),	// <stdin>:3113:10
    .R1_clk  (clock),
    .W0_addr (replaceCacheAddr),	// src/main/scala/rv32e/cache/dcache.scala:107:31
    .W0_en   (_GEN_5),	// src/main/scala/rv32e/cache/dcache.scala:49:24, :56:27, :98:{26,32}
    .W0_clk  (clock),
    .W0_data (to_sram_r_bits_data),
    .W1_addr (hitCacheAddr),	// src/main/scala/rv32e/cache/dcache.scala:45:27
    .W1_en   (_GEN_4),	// src/main/scala/rv32e/cache/dcache.scala:56:27
    .W1_clk  (clock),
    .W1_data
      (_GEN_6[31:0] & from_LSU_bits_wmask | _dataArray_ext_R0_data
       & ~from_LSU_bits_wmask),	// src/main/scala/rv32e/cache/dcache.scala:30:33, :126:{28,56,65,76,78}
    .R0_data (_dataArray_ext_R0_data),
    .R1_data (to_sram_w_bits_data)
  );
  assign from_LSU_ready = _from_LSU_ready_output;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:56:27
  assign to_LSU_valid = _GEN_4 | _GEN_3;	// <stdin>:3113:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/cache/dcache.scala:56:27
  assign to_LSU_bits_data = hit ? _dataArray_ext_R0_data : 32'h0;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:30:33, :38:33, :155:29
  assign to_LSU_bits_bresp = _GEN_4;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:56:27
  assign to_sram_ar_valid = _to_sram_ar_valid_output;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:56:27
  assign to_sram_ar_bits_addr =
    _to_sram_ar_valid_output ? {from_LSU_bits_addr[31:4], 4'h0} : 32'h0;	// <stdin>:3113:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/cache/dcache.scala:55:31, :56:27, :139:{93,106}, :155:29
  assign to_sram_ar_bits_len = {6'h0, {2{_to_sram_ar_valid_output}}};	// <stdin>:3113:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/cache/dcache.scala:56:27, :141:27
  assign to_sram_r_ready = _to_sram_r_ready_output;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:56:27
  assign to_sram_aw_valid = _to_sram_aw_valid_output;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:56:27
  assign to_sram_aw_bits_addr =
    {_GEN_7[from_LSU_bits_addr[7:4]], from_LSU_bits_addr[7:4], 4'h0};	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:22:41, :55:31, :145:33
  assign to_sram_aw_bits_len = {6'h0, {2{_to_sram_aw_valid_output}}};	// <stdin>:3113:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/cache/dcache.scala:56:27, :141:27, :147:27
  assign to_sram_w_valid = _to_sram_w_valid_output;	// <stdin>:3113:10, src/main/scala/rv32e/cache/dcache.scala:56:27
endmodule

