// Generated by CIRCT firtool-1.43.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module iCacheV2(	// <stdin>:2730:10
  input         clock,	// <stdin>:2731:11
                reset,	// <stdin>:2732:11
                from_IFU_valid,	// src/main/scala/rv32e/cache/icache.scala:113:22
  input  [31:0] from_IFU_bits_addr,	// src/main/scala/rv32e/cache/icache.scala:113:22
  input         to_sram_ar_ready,	// src/main/scala/rv32e/cache/icache.scala:115:22
                to_sram_r_valid,	// src/main/scala/rv32e/cache/icache.scala:115:22
  input  [31:0] to_sram_r_bits_data,	// src/main/scala/rv32e/cache/icache.scala:115:22
  input         to_sram_r_bits_last,	// src/main/scala/rv32e/cache/icache.scala:115:22
  output        from_IFU_ready,	// src/main/scala/rv32e/cache/icache.scala:113:22
                to_IFU_valid,	// src/main/scala/rv32e/cache/icache.scala:114:22
  output [31:0] to_IFU_bits_data,	// src/main/scala/rv32e/cache/icache.scala:114:22
  output        to_sram_ar_valid,	// src/main/scala/rv32e/cache/icache.scala:115:22
  output [31:0] to_sram_ar_bits_addr,	// src/main/scala/rv32e/cache/icache.scala:115:22
  output [7:0]  to_sram_ar_bits_len,	// src/main/scala/rv32e/cache/icache.scala:115:22
  output        to_sram_r_ready	// src/main/scala/rv32e/cache/icache.scala:115:22
);

  wire [31:0]       _dataArray_ext_R0_data;	// src/main/scala/rv32e/cache/icache.scala:127:33
  reg               replace_set;	// src/main/scala/rv32e/cache/icache.scala:117:30
  reg               random_num;	// src/main/scala/rv32e/cache/icache.scala:123:29
  reg  [23:0]       tagArray_0_0;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_1;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_2;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_3;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_4;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_5;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_6;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_7;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_8;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_9;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_10;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_11;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_12;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_13;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_14;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_0_15;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_0;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_1;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_2;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_3;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_4;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_5;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_6;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_7;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_8;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_9;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_10;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_11;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_12;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_13;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_14;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg  [23:0]       tagArray_1_15;	// src/main/scala/rv32e/cache/icache.scala:128:29
  reg               validArray_0_0;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_1;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_2;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_3;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_4;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_5;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_6;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_7;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_8;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_9;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_10;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_11;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_12;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_13;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_14;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_0_15;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_0;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_1;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_2;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_3;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_4;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_5;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_6;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_7;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_8;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_9;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_10;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_11;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_12;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_13;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_14;	// src/main/scala/rv32e/cache/icache.scala:129:29
  reg               validArray_1_15;	// src/main/scala/rv32e/cache/icache.scala:129:29
  wire [15:0][23:0] _GEN =
    {{tagArray_0_15},
     {tagArray_0_14},
     {tagArray_0_13},
     {tagArray_0_12},
     {tagArray_0_11},
     {tagArray_0_10},
     {tagArray_0_9},
     {tagArray_0_8},
     {tagArray_0_7},
     {tagArray_0_6},
     {tagArray_0_5},
     {tagArray_0_4},
     {tagArray_0_3},
     {tagArray_0_2},
     {tagArray_0_1},
     {tagArray_0_0}};	// src/main/scala/rv32e/cache/icache.scala:128:29, :132:14
  wire [15:0]       _GEN_0 =
    {{validArray_0_15},
     {validArray_0_14},
     {validArray_0_13},
     {validArray_0_12},
     {validArray_0_11},
     {validArray_0_10},
     {validArray_0_9},
     {validArray_0_8},
     {validArray_0_7},
     {validArray_0_6},
     {validArray_0_5},
     {validArray_0_4},
     {validArray_0_3},
     {validArray_0_2},
     {validArray_0_1},
     {validArray_0_0}};	// src/main/scala/rv32e/cache/icache.scala:129:29, :132:44
  wire [15:0][23:0] _GEN_1 =
    {{tagArray_1_15},
     {tagArray_1_14},
     {tagArray_1_13},
     {tagArray_1_12},
     {tagArray_1_11},
     {tagArray_1_10},
     {tagArray_1_9},
     {tagArray_1_8},
     {tagArray_1_7},
     {tagArray_1_6},
     {tagArray_1_5},
     {tagArray_1_4},
     {tagArray_1_3},
     {tagArray_1_2},
     {tagArray_1_1},
     {tagArray_1_0}};	// src/main/scala/rv32e/cache/icache.scala:128:29, :132:14
  wire              SetId = from_IFU_bits_addr[31:8] == _GEN_1[from_IFU_bits_addr[7:4]];	// src/main/scala/rv32e/cache/icache.scala:119:41, :120:41, :132:14
  wire [15:0]       _GEN_2 =
    {{validArray_1_15},
     {validArray_1_14},
     {validArray_1_13},
     {validArray_1_12},
     {validArray_1_11},
     {validArray_1_10},
     {validArray_1_9},
     {validArray_1_8},
     {validArray_1_7},
     {validArray_1_6},
     {validArray_1_5},
     {validArray_1_4},
     {validArray_1_3},
     {validArray_1_2},
     {validArray_1_1},
     {validArray_1_0}};	// src/main/scala/rv32e/cache/icache.scala:129:29, :132:44
  wire              hit =
    from_IFU_bits_addr[31:8] == _GEN[from_IFU_bits_addr[7:4]]
    & _GEN_0[from_IFU_bits_addr[7:4]] | SetId & _GEN_2[from_IFU_bits_addr[7:4]];	// src/main/scala/rv32e/cache/icache.scala:119:41, :120:41, :132:{14,44}, :134:33
  reg  [1:0]        off;	// src/main/scala/rv32e/cache/icache.scala:143:24
  reg  [2:0]        state_cache;	// src/main/scala/rv32e/cache/icache.scala:146:30
  wire              _from_IFU_ready_output = state_cache == 3'h0;	// src/main/scala/rv32e/cache/icache.scala:146:30, :147:26
  wire              _GEN_3 = state_cache == 3'h1;	// src/main/scala/rv32e/cache/icache.scala:146:30, :147:26, :150:35
  wire              _to_sram_ar_valid_output = state_cache == 3'h2;	// src/main/scala/rv32e/cache/icache.scala:146:30, :147:26, :150:35
  wire              _to_sram_r_ready_output = state_cache == 3'h3;	// src/main/scala/rv32e/cache/icache.scala:146:30, :147:26, :160:31
  wire              _GEN_4 = _to_sram_r_ready_output & to_sram_r_valid;	// src/main/scala/rv32e/cache/icache.scala:143:24, :147:26, :167:{25,31}
  always @(posedge clock) begin	// <stdin>:2731:11
    if (reset) begin	// <stdin>:2731:11
      replace_set <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:117:30
      random_num <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:123:29
      tagArray_0_0 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_1 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_2 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_3 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_4 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_5 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_6 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_7 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_8 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_9 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_10 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_11 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_12 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_13 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_14 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_0_15 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_0 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_1 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_2 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_3 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_4 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_5 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_6 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_7 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_8 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_9 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_10 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_11 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_12 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_13 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_14 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      tagArray_1_15 <= 24'h0;	// src/main/scala/rv32e/cache/icache.scala:128:{29,63}
      validArray_0_0 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_1 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_2 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_3 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_4 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_5 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_6 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_7 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_8 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_9 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_10 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_11 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_12 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_13 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_14 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_0_15 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_0 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_1 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_2 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_3 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_4 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_5 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_6 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_7 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_8 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_9 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_10 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_11 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_12 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_13 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_14 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      validArray_1_15 <= 1'h0;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
      off <= 2'h0;	// src/main/scala/rv32e/cache/icache.scala:143:24
      state_cache <= 3'h0;	// src/main/scala/rv32e/cache/icache.scala:146:30
    end
    else begin	// <stdin>:2731:11
      automatic logic            _GEN_5 = _from_IFU_ready_output | _GEN_3;	// src/main/scala/rv32e/cache/icache.scala:117:30, :147:26
      automatic logic            _GEN_6 = from_IFU_bits_addr[7:4] == 4'h0;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_7;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_8 = from_IFU_bits_addr[7:4] == 4'h1;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_9;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_10 = from_IFU_bits_addr[7:4] == 4'h2;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_11;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_12 = from_IFU_bits_addr[7:4] == 4'h3;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_13;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_14 = from_IFU_bits_addr[7:4] == 4'h4;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_15;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_16 = from_IFU_bits_addr[7:4] == 4'h5;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_17;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_18 = from_IFU_bits_addr[7:4] == 4'h6;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_19;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_20 = from_IFU_bits_addr[7:4] == 4'h7;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_21;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_22 = from_IFU_bits_addr[7:4] == 4'h8;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_23;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_24 = from_IFU_bits_addr[7:4] == 4'h9;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_25;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_26 = from_IFU_bits_addr[7:4] == 4'hA;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_27;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_28 = from_IFU_bits_addr[7:4] == 4'hB;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_29;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_30 = from_IFU_bits_addr[7:4] == 4'hC;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_31;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_32 = from_IFU_bits_addr[7:4] == 4'hD;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_33;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_34 = from_IFU_bits_addr[7:4] == 4'hE;	// src/main/scala/rv32e/cache/icache.scala:119:41, :183:50
      automatic logic            _GEN_35;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_36;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_37;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_38;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_39;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_40;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_41;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_42;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_43;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_44;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_45;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_46;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_47;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_48;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_49;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_50;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_51;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic            _GEN_52;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      automatic logic [7:0][2:0] _GEN_53;	// src/main/scala/rv32e/cache/icache.scala:146:30, :147:26, :149:34, :156:25, :160:25, :166:25, :172:25
      _GEN_7 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_6;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_9 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_8;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_11 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_10;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_13 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_12;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_15 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_14;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_17 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_16;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_19 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_18;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_21 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_20;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_23 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_22;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_25 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_24;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_27 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_26;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_29 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_28;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_31 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_30;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_33 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_32;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_35 = _GEN_4 & to_sram_r_bits_last & ~replace_set & _GEN_34;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_36 =
        _GEN_4 & to_sram_r_bits_last & ~replace_set & (&(from_IFU_bits_addr[7:4]));	// src/main/scala/rv32e/cache/icache.scala:117:30, :119:41, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_37 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_6;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_38 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_8;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_39 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_10;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_40 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_12;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_41 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_14;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_42 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_16;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_43 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_18;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_44 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_20;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_45 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_22;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_46 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_24;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_47 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_26;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_48 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_28;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_49 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_30;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_50 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_32;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_51 = _GEN_4 & to_sram_r_bits_last & replace_set & _GEN_34;	// src/main/scala/rv32e/cache/icache.scala:117:30, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      _GEN_52 = _GEN_4 & to_sram_r_bits_last & replace_set & (&(from_IFU_bits_addr[7:4]));	// src/main/scala/rv32e/cache/icache.scala:117:30, :119:41, :129:29, :143:24, :147:26, :167:{25,31}, :180:58, :182:35, :183:50
      if (_GEN_5 | ~_to_sram_ar_valid_output) begin	// src/main/scala/rv32e/cache/icache.scala:117:30, :147:26
      end
      else	// src/main/scala/rv32e/cache/icache.scala:117:30, :147:26
        replace_set <= random_num;	// src/main/scala/rv32e/cache/icache.scala:117:30, :123:29
      random_num <= random_num - 1'h1;	// src/main/scala/rv32e/cache/icache.scala:123:29, :124:29
      if (_GEN_7)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_0 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_9)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_1 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_11)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_2 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_13)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_3 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_15)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_4 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_17)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_5 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_19)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_6 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_21)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_7 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_23)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_8 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_25)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_9 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_27)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_10 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_29)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_11 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_31)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_12 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_33)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_13 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_35)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_14 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_36)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_0_15 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_37)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_0 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_38)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_1 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_39)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_2 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_40)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_3 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_41)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_4 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_42)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_5 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_43)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_6 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_44)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_7 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_45)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_8 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_46)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_9 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_47)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_10 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_48)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_11 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_49)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_12 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_50)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_13 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_51)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_14 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      if (_GEN_52)	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
        tagArray_1_15 <= from_IFU_bits_addr[31:8];	// src/main/scala/rv32e/cache/icache.scala:120:41, :128:29
      validArray_0_0 <= _GEN_7 | validArray_0_0;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_1 <= _GEN_9 | validArray_0_1;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_2 <= _GEN_11 | validArray_0_2;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_3 <= _GEN_13 | validArray_0_3;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_4 <= _GEN_15 | validArray_0_4;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_5 <= _GEN_17 | validArray_0_5;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_6 <= _GEN_19 | validArray_0_6;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_7 <= _GEN_21 | validArray_0_7;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_8 <= _GEN_23 | validArray_0_8;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_9 <= _GEN_25 | validArray_0_9;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_10 <= _GEN_27 | validArray_0_10;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_11 <= _GEN_29 | validArray_0_11;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_12 <= _GEN_31 | validArray_0_12;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_13 <= _GEN_33 | validArray_0_13;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_14 <= _GEN_35 | validArray_0_14;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_0_15 <= _GEN_36 | validArray_0_15;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_0 <= _GEN_37 | validArray_1_0;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_1 <= _GEN_38 | validArray_1_1;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_2 <= _GEN_39 | validArray_1_2;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_3 <= _GEN_40 | validArray_1_3;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_4 <= _GEN_41 | validArray_1_4;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_5 <= _GEN_42 | validArray_1_5;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_6 <= _GEN_43 | validArray_1_6;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_7 <= _GEN_44 | validArray_1_7;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_8 <= _GEN_45 | validArray_1_8;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_9 <= _GEN_46 | validArray_1_9;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_10 <= _GEN_47 | validArray_1_10;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_11 <= _GEN_48 | validArray_1_11;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_12 <= _GEN_49 | validArray_1_12;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_13 <= _GEN_50 | validArray_1_13;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_14 <= _GEN_51 | validArray_1_14;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      validArray_1_15 <= _GEN_52 | validArray_1_15;	// src/main/scala/rv32e/cache/icache.scala:129:29, :180:58, :182:35, :183:50
      if (~_GEN_5) begin	// src/main/scala/rv32e/cache/icache.scala:117:30, :147:26
        if (_to_sram_ar_valid_output)	// src/main/scala/rv32e/cache/icache.scala:147:26
          off <= 2'h0;	// src/main/scala/rv32e/cache/icache.scala:143:24
        else if (_GEN_4)	// src/main/scala/rv32e/cache/icache.scala:143:24, :147:26, :167:{25,31}
          off <= off + 2'h1;	// src/main/scala/rv32e/cache/icache.scala:143:24, :160:31, :167:51
      end
      _GEN_53 =
        {{state_cache},
         {state_cache},
         {state_cache},
         {3'h1},
         {to_sram_r_bits_last ? 3'h4 : 3'h3},
         {{2'h1, to_sram_ar_ready & _to_sram_ar_valid_output}},
         {3'h0},
         {_from_IFU_ready_output & from_IFU_valid ? (hit ? 3'h1 : 3'h2) : 3'h0}};	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rv32e/cache/icache.scala:134:33, :146:30, :147:26, :149:34, :150:{29,35}, :152:29, :156:25, :160:{25,31}, :166:{25,31}, :172:25
      state_cache <= _GEN_53[state_cache];	// src/main/scala/rv32e/cache/icache.scala:146:30, :147:26, :149:34, :156:25, :160:25, :166:25, :172:25
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:2730:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:2730:10
      `FIRRTL_BEFORE_INITIAL	// <stdin>:2730:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:2730:10
      automatic logic [31:0] _RANDOM[0:25];	// <stdin>:2730:10
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:2730:10
        `INIT_RANDOM_PROLOG_	// <stdin>:2730:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:2730:10
        for (logic [4:0] i = 5'h0; i < 5'h1A; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// <stdin>:2730:10
        end	// <stdin>:2730:10
        replace_set = _RANDOM[5'h0][0];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:117:30
        random_num = _RANDOM[5'h0][1];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:117:30, :123:29
        tagArray_0_0 = _RANDOM[5'h0][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:117:30, :128:29
        tagArray_0_1 = {_RANDOM[5'h0][31:26], _RANDOM[5'h1][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:117:30, :128:29
        tagArray_0_2 = {_RANDOM[5'h1][31:18], _RANDOM[5'h2][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_3 = {_RANDOM[5'h2][31:10], _RANDOM[5'h3][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_4 = _RANDOM[5'h3][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_5 = {_RANDOM[5'h3][31:26], _RANDOM[5'h4][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_6 = {_RANDOM[5'h4][31:18], _RANDOM[5'h5][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_7 = {_RANDOM[5'h5][31:10], _RANDOM[5'h6][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_8 = _RANDOM[5'h6][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_9 = {_RANDOM[5'h6][31:26], _RANDOM[5'h7][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_10 = {_RANDOM[5'h7][31:18], _RANDOM[5'h8][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_11 = {_RANDOM[5'h8][31:10], _RANDOM[5'h9][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_12 = _RANDOM[5'h9][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_13 = {_RANDOM[5'h9][31:26], _RANDOM[5'hA][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_14 = {_RANDOM[5'hA][31:18], _RANDOM[5'hB][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_0_15 = {_RANDOM[5'hB][31:10], _RANDOM[5'hC][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_0 = _RANDOM[5'hC][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_1 = {_RANDOM[5'hC][31:26], _RANDOM[5'hD][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_2 = {_RANDOM[5'hD][31:18], _RANDOM[5'hE][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_3 = {_RANDOM[5'hE][31:10], _RANDOM[5'hF][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_4 = _RANDOM[5'hF][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_5 = {_RANDOM[5'hF][31:26], _RANDOM[5'h10][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_6 = {_RANDOM[5'h10][31:18], _RANDOM[5'h11][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_7 = {_RANDOM[5'h11][31:10], _RANDOM[5'h12][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_8 = _RANDOM[5'h12][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_9 = {_RANDOM[5'h12][31:26], _RANDOM[5'h13][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_10 = {_RANDOM[5'h13][31:18], _RANDOM[5'h14][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_11 = {_RANDOM[5'h14][31:10], _RANDOM[5'h15][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_12 = _RANDOM[5'h15][25:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_13 = {_RANDOM[5'h15][31:26], _RANDOM[5'h16][17:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_14 = {_RANDOM[5'h16][31:18], _RANDOM[5'h17][9:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        tagArray_1_15 = {_RANDOM[5'h17][31:10], _RANDOM[5'h18][1:0]};	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29
        validArray_0_0 = _RANDOM[5'h18][2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_1 = _RANDOM[5'h18][3];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_2 = _RANDOM[5'h18][4];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_3 = _RANDOM[5'h18][5];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_4 = _RANDOM[5'h18][6];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_5 = _RANDOM[5'h18][7];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_6 = _RANDOM[5'h18][8];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_7 = _RANDOM[5'h18][9];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_8 = _RANDOM[5'h18][10];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_9 = _RANDOM[5'h18][11];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_10 = _RANDOM[5'h18][12];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_11 = _RANDOM[5'h18][13];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_12 = _RANDOM[5'h18][14];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_13 = _RANDOM[5'h18][15];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_14 = _RANDOM[5'h18][16];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_0_15 = _RANDOM[5'h18][17];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_0 = _RANDOM[5'h18][18];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_1 = _RANDOM[5'h18][19];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_2 = _RANDOM[5'h18][20];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_3 = _RANDOM[5'h18][21];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_4 = _RANDOM[5'h18][22];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_5 = _RANDOM[5'h18][23];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_6 = _RANDOM[5'h18][24];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_7 = _RANDOM[5'h18][25];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_8 = _RANDOM[5'h18][26];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_9 = _RANDOM[5'h18][27];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_10 = _RANDOM[5'h18][28];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_11 = _RANDOM[5'h18][29];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_12 = _RANDOM[5'h18][30];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_13 = _RANDOM[5'h18][31];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:128:29, :129:29
        validArray_1_14 = _RANDOM[5'h19][0];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
        validArray_1_15 = _RANDOM[5'h19][1];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29
        off = _RANDOM[5'h19][3:2];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29, :143:24
        state_cache = _RANDOM[5'h19][6:4];	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:129:29, :146:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:2730:10
      `FIRRTL_AFTER_INITIAL	// <stdin>:2730:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  dataArray_combMem dataArray_ext (	// src/main/scala/rv32e/cache/icache.scala:127:33
    .R0_addr ({SetId, from_IFU_bits_addr[7:2]}),	// src/main/scala/rv32e/cache/icache.scala:132:14, :141:27
    .R0_en   (1'h1),	// <stdin>:2730:10
    .R0_clk  (clock),
    .W0_addr ({replace_set, from_IFU_bits_addr[7:4], off}),	// src/main/scala/rv32e/cache/icache.scala:117:30, :119:41, :143:24, :179:31
    .W0_en   (_GEN_4),	// src/main/scala/rv32e/cache/icache.scala:143:24, :147:26, :167:{25,31}
    .W0_clk  (clock),
    .W0_data (to_sram_r_bits_data),
    .R0_data (_dataArray_ext_R0_data)
  );
  assign from_IFU_ready = _from_IFU_ready_output;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:147:26
  assign to_IFU_valid = _GEN_3;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:147:26
  assign to_IFU_bits_data = hit ? _dataArray_ext_R0_data : 32'h13;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:127:33, :134:33, :208:28
  assign to_sram_ar_valid = _to_sram_ar_valid_output;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:147:26
  assign to_sram_ar_bits_addr =
    _to_sram_ar_valid_output ? {from_IFU_bits_addr[31:4], 4'h0} : 32'h0;	// <stdin>:2730:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/cache/icache.scala:147:26, :166:31, :183:50, :191:{91,104}
  assign to_sram_ar_bits_len = {6'h0, {2{_to_sram_ar_valid_output}}};	// <stdin>:2730:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/cache/icache.scala:147:26, :193:27
  assign to_sram_r_ready = _to_sram_r_ready_output;	// <stdin>:2730:10, src/main/scala/rv32e/cache/icache.scala:147:26
endmodule

