// Generated by CIRCT firtool-1.43.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Lsu_cache(	// <stdin>:2186:10
  input         clock,	// <stdin>:2187:11
                reset,	// <stdin>:2188:11
                io_in_valid,	// src/main/scala/rv32e/fu/lsu.scala:297:16
                io_in_mem_wen,	// src/main/scala/rv32e/fu/lsu.scala:297:16
  input  [31:0] io_in_addr,	// src/main/scala/rv32e/fu/lsu.scala:297:16
                io_in_wdata,	// src/main/scala/rv32e/fu/lsu.scala:297:16
  input  [3:0]  io_in_op,	// src/main/scala/rv32e/fu/lsu.scala:297:16
  input         to_cache_ready,	// src/main/scala/rv32e/fu/lsu.scala:301:24
                from_cache_valid,	// src/main/scala/rv32e/fu/lsu.scala:302:24
  input  [31:0] from_cache_bits_data,	// src/main/scala/rv32e/fu/lsu.scala:302:24
  input         from_cache_bits_bresp,	// src/main/scala/rv32e/fu/lsu.scala:302:24
  output [31:0] io_out_rdata,	// src/main/scala/rv32e/fu/lsu.scala:297:16
  output        io_out_end,	// src/main/scala/rv32e/fu/lsu.scala:297:16
                io_out_idle,	// src/main/scala/rv32e/fu/lsu.scala:297:16
                to_cache_valid,	// src/main/scala/rv32e/fu/lsu.scala:301:24
  output [31:0] to_cache_bits_addr,	// src/main/scala/rv32e/fu/lsu.scala:301:24
                to_cache_bits_wdata,	// src/main/scala/rv32e/fu/lsu.scala:301:24
  output        to_cache_bits_is_write,	// src/main/scala/rv32e/fu/lsu.scala:301:24
  output [31:0] to_cache_bits_wmask	// src/main/scala/rv32e/fu/lsu.scala:301:24
);

  reg  [2:0]       state_lsu;	// src/main/scala/rv32e/fu/lsu.scala:306:28
  wire             _GEN = state_lsu == 3'h3;	// src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :311:31
  wire             _GEN_0 = state_lsu == 3'h4;	// src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :328:29
  wire             _GEN_1 = io_in_addr[1:0] == 2'h2;	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:342:31
  wire [3:0][31:0] _GEN_2 =
    {{{{24{from_cache_bits_data[31]}}, from_cache_bits_data[31:24]}},
     {{{24{from_cache_bits_data[23]}}, from_cache_bits_data[23:16]}},
     {{{24{from_cache_bits_data[15]}}, from_cache_bits_data[15:8]}},
     {{{24{from_cache_bits_data[7]}}, from_cache_bits_data[7:0]}}};	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:356:{19,24,42,62}, :357:{19,24,42,62}, :358:{19,24,42,62}, :359:{19,24,42,62}
  wire [3:0][7:0]  _GEN_3 =
    {{from_cache_bits_data[31:24]},
     {from_cache_bits_data[23:16]},
     {from_cache_bits_data[15:8]},
     {from_cache_bits_data[7:0]}};	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:356:62, :357:62, :358:62, :359:62, :363:19, :364:19, :365:19, :366:19
  wire             _GEN_4 = io_in_addr[1:0] == 2'h0;	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:342:31
  wire             _to_cache_valid_output = _GEN | state_lsu == 3'h1;	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :313:31
  always @(posedge clock) begin	// <stdin>:2187:11
    if (reset)	// <stdin>:2187:11
      state_lsu <= 3'h0;	// src/main/scala/rv32e/fu/lsu.scala:306:28
    else begin	// <stdin>:2187:11
      automatic logic            _GEN_5 = to_cache_ready & _to_cache_valid_output;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/chisel3/util/Mux.scala:77:13
      automatic logic            _GEN_6;	// src/main/scala/chisel3/util/Decoupled.scala:52:35
      automatic logic [7:0][2:0] _GEN_7;	// src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :309:32, :320:23, :323:23, :328:23, :331:23, :335:23
      _GEN_6 = (_GEN_0 | state_lsu == 3'h2) & from_cache_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :320:29
      _GEN_7 =
        {{state_lsu},
         {state_lsu},
         {3'h0},
         {{2'h2, _GEN_6 & from_cache_bits_bresp}},
         {_GEN_5 ? 3'h4 : 3'h3},
         {_GEN_6 ? 3'h5 : 3'h2},
         {_GEN_5 ? 3'h2 : 3'h1},
         {io_in_valid ? {1'h0, io_in_mem_wen, 1'h1} : 3'h0}};	// <stdin>:2186:10, src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :309:32, :310:38, :311:31, :313:31, :316:27, :320:{23,29}, :323:{23,29}, :328:{23,29}, :331:{23,29,46}, :335:23
      state_lsu <= _GEN_7[state_lsu];	// src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :309:32, :320:23, :323:23, :328:23, :331:23, :335:23
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:2186:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:2186:10
      `FIRRTL_BEFORE_INITIAL	// <stdin>:2186:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:2186:10
      automatic logic [31:0] _RANDOM[0:0];	// <stdin>:2186:10
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:2186:10
        `INIT_RANDOM_PROLOG_	// <stdin>:2186:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:2186:10
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// <stdin>:2186:10
        state_lsu = _RANDOM[/*Zero width*/ 1'b0][2:0];	// <stdin>:2186:10, src/main/scala/rv32e/fu/lsu.scala:306:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:2186:10
      `FIRRTL_AFTER_INITIAL	// <stdin>:2186:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_rdata =
    io_in_op == 4'h3
      ? from_cache_bits_data
      : io_in_op == 4'h5
          ? (_GEN_1
               ? {16'h0, from_cache_bits_data[31:16]}
               : _GEN_4 ? {16'h0, from_cache_bits_data[15:0]} : 32'h0)
          : io_in_op == 4'h2
              ? (_GEN_1
                   ? {{16{from_cache_bits_data[31]}}, from_cache_bits_data[31:16]}
                   : _GEN_4
                       ? {{16{from_cache_bits_data[15]}}, from_cache_bits_data[15:0]}
                       : 32'h0)
              : io_in_op == 4'h4
                  ? {24'h0, _GEN_3[io_in_addr[1:0]]}
                  : io_in_op == 4'h1 ? _GEN_2[io_in_addr[1:0]] : 32'h0;	// <stdin>:2186:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:342:31, :356:24, :357:42, :359:42, :363:19, :364:19, :365:19, :366:19, :370:{19,24,62}, :371:{19,24,62}, :375:19, :376:19
  assign io_out_end = state_lsu == 3'h5;	// <stdin>:2186:10, src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24, :323:29
  assign io_out_idle = state_lsu == 3'h0;	// <stdin>:2186:10, src/main/scala/rv32e/fu/lsu.scala:306:28, :307:24
  assign to_cache_valid = _to_cache_valid_output;	// <stdin>:2186:10, src/main/scala/chisel3/util/Mux.scala:77:13
  assign to_cache_bits_addr = io_in_addr;	// <stdin>:2186:10
  assign to_cache_bits_wdata = io_in_wdata;	// <stdin>:2186:10
  assign to_cache_bits_is_write = _GEN_0 | _GEN;	// <stdin>:2186:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:307:24
  assign to_cache_bits_wmask =
    io_in_op == 4'h8
      ? 32'hFFFFFFFF
      : io_in_op == 4'h7
          ? (_GEN_1 ? 32'hFFFF0000 : {16'h0, {16{_GEN_4}}})
          : io_in_op == 4'h6
              ? ((&(io_in_addr[1:0]))
                   ? 32'hFF000000
                   : {8'h0,
                      _GEN_1
                        ? 24'hFF0000
                        : {8'h0, io_in_addr[1:0] == 2'h1 ? 16'hFF00 : 16'hFF}})
              : 32'h0;	// <stdin>:2186:10, src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rv32e/fu/lsu.scala:342:31, :370:24, :398:17
endmodule

