/* verilator lint_off DECLFILENAME */
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off UNDRIVEN */
/* verilator lint_off UNOPTFLAT */
/* verilator lint_off WIDTHEXPAND */
// Generated by CIRCT firtool-1.43.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module top(	// <stdin>:3611:10
  input         clock,	// <stdin>:3612:11
                reset,	// <stdin>:3613:11
  output [31:0] io_out_inst,	// src/main/scala/rv32e/core.scala:35:16
                io_out_pc,	// src/main/scala/rv32e/core.scala:35:16
                io_out_difftest_mcause,	// src/main/scala/rv32e/core.scala:35:16
                io_out_difftest_mepc,	// src/main/scala/rv32e/core.scala:35:16
                io_out_difftest_mstatus,	// src/main/scala/rv32e/core.scala:35:16
                io_out_difftest_mtvec,	// src/main/scala/rv32e/core.scala:35:16
  output        io_out_wb	// src/main/scala/rv32e/core.scala:35:16
);

  wire        _sram_i2_axi_ar_ready;	// src/main/scala/rv32e/core.scala:68:27
  wire        _sram_i2_axi_r_valid;	// src/main/scala/rv32e/core.scala:68:27
  wire [31:0] _sram_i2_axi_r_bits_data;	// src/main/scala/rv32e/core.scala:68:27
  wire        _sram_i2_axi_r_bits_last;	// src/main/scala/rv32e/core.scala:68:27
  wire        _sram_i2_axi_aw_ready;	// src/main/scala/rv32e/core.scala:68:27
  wire        _sram_i2_axi_w_ready;	// src/main/scala/rv32e/core.scala:68:27
  wire        _dcache_from_LSU_ready;	// src/main/scala/rv32e/core.scala:67:27
  wire        _dcache_to_LSU_valid;	// src/main/scala/rv32e/core.scala:67:27
  wire [31:0] _dcache_to_LSU_bits_data;	// src/main/scala/rv32e/core.scala:67:27
  wire        _dcache_to_LSU_bits_bresp;	// src/main/scala/rv32e/core.scala:67:27
  wire        _dcache_to_sram_ar_valid;	// src/main/scala/rv32e/core.scala:67:27
  wire [31:0] _dcache_to_sram_ar_bits_addr;	// src/main/scala/rv32e/core.scala:67:27
  wire [7:0]  _dcache_to_sram_ar_bits_len;	// src/main/scala/rv32e/core.scala:67:27
  wire        _dcache_to_sram_r_ready;	// src/main/scala/rv32e/core.scala:67:27
  wire        _dcache_to_sram_aw_valid;	// src/main/scala/rv32e/core.scala:67:27
  wire [31:0] _dcache_to_sram_aw_bits_addr;	// src/main/scala/rv32e/core.scala:67:27
  wire [7:0]  _dcache_to_sram_aw_bits_len;	// src/main/scala/rv32e/core.scala:67:27
  wire        _dcache_to_sram_w_valid;	// src/main/scala/rv32e/core.scala:67:27
  wire [31:0] _dcache_to_sram_w_bits_data;	// src/main/scala/rv32e/core.scala:67:27
  wire        _sram_i_axi_ar_ready;	// src/main/scala/rv32e/core.scala:57:27
  wire        _sram_i_axi_r_valid;	// src/main/scala/rv32e/core.scala:57:27
  wire [31:0] _sram_i_axi_r_bits_data;	// src/main/scala/rv32e/core.scala:57:27
  wire        _sram_i_axi_r_bits_last;	// src/main/scala/rv32e/core.scala:57:27
  wire        _icache_from_IFU_ready;	// src/main/scala/rv32e/core.scala:56:27
  wire        _icache_to_IFU_valid;	// src/main/scala/rv32e/core.scala:56:27
  wire [31:0] _icache_to_IFU_bits_data;	// src/main/scala/rv32e/core.scala:56:27
  wire        _icache_to_sram_ar_valid;	// src/main/scala/rv32e/core.scala:56:27
  wire [31:0] _icache_to_sram_ar_bits_addr;	// src/main/scala/rv32e/core.scala:56:27
  wire [7:0]  _icache_to_sram_ar_bits_len;	// src/main/scala/rv32e/core.scala:56:27
  wire        _icache_to_sram_r_ready;	// src/main/scala/rv32e/core.scala:56:27
  wire        _IFU_i_to_IDU_valid;	// src/main/scala/rv32e/core.scala:55:27
  wire [31:0] _IFU_i_to_IDU_bits_inst;	// src/main/scala/rv32e/core.scala:55:27
  wire [31:0] _IFU_i_to_IDU_bits_pc;	// src/main/scala/rv32e/core.scala:55:27
  wire        _IFU_i_to_cache_valid;	// src/main/scala/rv32e/core.scala:55:27
  wire [31:0] _IFU_i_to_cache_bits_addr;	// src/main/scala/rv32e/core.scala:55:27
  wire        _WBU_i_to_ISU_bits_reg_wen;	// src/main/scala/rv32e/core.scala:42:27
  wire [31:0] _WBU_i_to_ISU_bits_wdata;	// src/main/scala/rv32e/core.scala:42:27
  wire [4:0]  _WBU_i_to_ISU_bits_rd;	// src/main/scala/rv32e/core.scala:42:27
  wire        _WBU_i_to_IFU_valid;	// src/main/scala/rv32e/core.scala:42:27
  wire        _EXU_i_from_ISU_ready;	// src/main/scala/rv32e/core.scala:41:27
  wire        _EXU_i_to_WBU_valid;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_to_WBU_bits_alu_result;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_to_WBU_bits_mdu_result;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_to_WBU_bits_lsu_rdata;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_to_WBU_bits_csr_rdata;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_to_WBU_bits_pc;	// src/main/scala/rv32e/core.scala:41:27
  wire        _EXU_i_to_WBU_bits_reg_wen;	// src/main/scala/rv32e/core.scala:41:27
  wire [4:0]  _EXU_i_to_WBU_bits_rd;	// src/main/scala/rv32e/core.scala:41:27
  wire [2:0]  _EXU_i_to_WBU_bits_fu_op;	// src/main/scala/rv32e/core.scala:41:27
  wire        _EXU_i_to_IFU_bits_bru_ctrl_br;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_to_IFU_bits_bru_addr;	// src/main/scala/rv32e/core.scala:41:27
  wire        _EXU_i_to_IFU_bits_csr_ctrl_br;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_to_IFU_bits_csr_addr;	// src/main/scala/rv32e/core.scala:41:27
  wire        _EXU_i_lsu_to_cache_valid;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_lsu_to_cache_bits_addr;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_lsu_to_cache_bits_wdata;	// src/main/scala/rv32e/core.scala:41:27
  wire        _EXU_i_lsu_to_cache_bits_is_write;	// src/main/scala/rv32e/core.scala:41:27
  wire [31:0] _EXU_i_lsu_to_cache_bits_wmask;	// src/main/scala/rv32e/core.scala:41:27
  wire        _ISU_i_to_EXU_valid;	// src/main/scala/rv32e/core.scala:40:27
  wire [31:0] _ISU_i_to_EXU_bits_imm;	// src/main/scala/rv32e/core.scala:40:27
  wire [31:0] _ISU_i_to_EXU_bits_pc;	// src/main/scala/rv32e/core.scala:40:27
  wire [31:0] _ISU_i_to_EXU_bits_rdata1;	// src/main/scala/rv32e/core.scala:40:27
  wire [31:0] _ISU_i_to_EXU_bits_rdata2;	// src/main/scala/rv32e/core.scala:40:27
  wire [4:0]  _ISU_i_to_EXU_bits_rd;	// src/main/scala/rv32e/core.scala:40:27
  wire        _ISU_i_to_EXU_bits_ctrl_sig_reg_wen;	// src/main/scala/rv32e/core.scala:40:27
  wire [2:0]  _ISU_i_to_EXU_bits_ctrl_sig_fu_op;	// src/main/scala/rv32e/core.scala:40:27
  wire        _ISU_i_to_EXU_bits_ctrl_sig_mem_wen;	// src/main/scala/rv32e/core.scala:40:27
  wire        _ISU_i_to_EXU_bits_ctrl_sig_is_ebreak;	// src/main/scala/rv32e/core.scala:40:27
  wire        _ISU_i_to_EXU_bits_ctrl_sig_not_impl;	// src/main/scala/rv32e/core.scala:40:27
  wire [1:0]  _ISU_i_to_EXU_bits_ctrl_sig_src1_op;	// src/main/scala/rv32e/core.scala:40:27
  wire [1:0]  _ISU_i_to_EXU_bits_ctrl_sig_src2_op;	// src/main/scala/rv32e/core.scala:40:27
  wire [3:0]  _ISU_i_to_EXU_bits_ctrl_sig_alu_op;	// src/main/scala/rv32e/core.scala:40:27
  wire [3:0]  _ISU_i_to_EXU_bits_ctrl_sig_lsu_op;	// src/main/scala/rv32e/core.scala:40:27
  wire [3:0]  _ISU_i_to_EXU_bits_ctrl_sig_bru_op;	// src/main/scala/rv32e/core.scala:40:27
  wire [2:0]  _ISU_i_to_EXU_bits_ctrl_sig_csr_op;	// src/main/scala/rv32e/core.scala:40:27
  wire [3:0]  _ISU_i_to_EXU_bits_ctrl_sig_mdu_op;	// src/main/scala/rv32e/core.scala:40:27
  wire        _IDU_i_to_ISU_valid;	// src/main/scala/rv32e/core.scala:39:27
  wire [31:0] _IDU_i_to_ISU_bits_imm;	// src/main/scala/rv32e/core.scala:39:27
  wire [31:0] _IDU_i_to_ISU_bits_pc;	// src/main/scala/rv32e/core.scala:39:27
  wire [4:0]  _IDU_i_to_ISU_bits_rs1;	// src/main/scala/rv32e/core.scala:39:27
  wire [4:0]  _IDU_i_to_ISU_bits_rs2;	// src/main/scala/rv32e/core.scala:39:27
  wire [4:0]  _IDU_i_to_ISU_bits_rd;	// src/main/scala/rv32e/core.scala:39:27
  wire        _IDU_i_to_ISU_bits_ctrl_sig_reg_wen;	// src/main/scala/rv32e/core.scala:39:27
  wire [2:0]  _IDU_i_to_ISU_bits_ctrl_sig_fu_op;	// src/main/scala/rv32e/core.scala:39:27
  wire        _IDU_i_to_ISU_bits_ctrl_sig_mem_wen;	// src/main/scala/rv32e/core.scala:39:27
  wire        _IDU_i_to_ISU_bits_ctrl_sig_is_ebreak;	// src/main/scala/rv32e/core.scala:39:27
  wire        _IDU_i_to_ISU_bits_ctrl_sig_not_impl;	// src/main/scala/rv32e/core.scala:39:27
  wire [1:0]  _IDU_i_to_ISU_bits_ctrl_sig_src1_op;	// src/main/scala/rv32e/core.scala:39:27
  wire [1:0]  _IDU_i_to_ISU_bits_ctrl_sig_src2_op;	// src/main/scala/rv32e/core.scala:39:27
  wire [3:0]  _IDU_i_to_ISU_bits_ctrl_sig_alu_op;	// src/main/scala/rv32e/core.scala:39:27
  wire [3:0]  _IDU_i_to_ISU_bits_ctrl_sig_lsu_op;	// src/main/scala/rv32e/core.scala:39:27
  wire [3:0]  _IDU_i_to_ISU_bits_ctrl_sig_bru_op;	// src/main/scala/rv32e/core.scala:39:27
  wire [2:0]  _IDU_i_to_ISU_bits_ctrl_sig_csr_op;	// src/main/scala/rv32e/core.scala:39:27
  wire [3:0]  _IDU_i_to_ISU_bits_ctrl_sig_mdu_op;	// src/main/scala/rv32e/core.scala:39:27
  reg  [31:0] EXU_i_from_ISU_bits_r_imm;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [31:0] EXU_i_from_ISU_bits_r_pc;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [31:0] EXU_i_from_ISU_bits_r_rdata1;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [31:0] EXU_i_from_ISU_bits_r_rdata2;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [4:0]  EXU_i_from_ISU_bits_r_rd;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg         EXU_i_from_ISU_bits_r_ctrl_sig_reg_wen;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [2:0]  EXU_i_from_ISU_bits_r_ctrl_sig_fu_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg         EXU_i_from_ISU_bits_r_ctrl_sig_mem_wen;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg         EXU_i_from_ISU_bits_r_ctrl_sig_is_ebreak;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg         EXU_i_from_ISU_bits_r_ctrl_sig_not_impl;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [1:0]  EXU_i_from_ISU_bits_r_ctrl_sig_src1_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [1:0]  EXU_i_from_ISU_bits_r_ctrl_sig_src2_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [3:0]  EXU_i_from_ISU_bits_r_ctrl_sig_alu_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [3:0]  EXU_i_from_ISU_bits_r_ctrl_sig_lsu_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [3:0]  EXU_i_from_ISU_bits_r_ctrl_sig_bru_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [2:0]  EXU_i_from_ISU_bits_r_ctrl_sig_csr_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  reg  [3:0]  EXU_i_from_ISU_bits_r_ctrl_sig_mdu_op;	// src/main/scala/rv32e/utils/Connect.scala:26:35
  always @(posedge clock) begin	// <stdin>:3612:11
    if (_ISU_i_to_EXU_valid & _EXU_i_from_ISU_ready) begin	// src/main/scala/rv32e/core.scala:40:27, :41:27, src/main/scala/rv32e/utils/Connect.scala:26:58
      EXU_i_from_ISU_bits_r_imm <= _ISU_i_to_EXU_bits_imm;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_pc <= _ISU_i_to_EXU_bits_pc;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_rdata1 <= _ISU_i_to_EXU_bits_rdata1;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_rdata2 <= _ISU_i_to_EXU_bits_rdata2;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_rd <= _ISU_i_to_EXU_bits_rd;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_reg_wen <= _ISU_i_to_EXU_bits_ctrl_sig_reg_wen;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_fu_op <= _ISU_i_to_EXU_bits_ctrl_sig_fu_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_mem_wen <= _ISU_i_to_EXU_bits_ctrl_sig_mem_wen;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_is_ebreak <= _ISU_i_to_EXU_bits_ctrl_sig_is_ebreak;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_not_impl <= _ISU_i_to_EXU_bits_ctrl_sig_not_impl;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_src1_op <= _ISU_i_to_EXU_bits_ctrl_sig_src1_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_src2_op <= _ISU_i_to_EXU_bits_ctrl_sig_src2_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_alu_op <= _ISU_i_to_EXU_bits_ctrl_sig_alu_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_lsu_op <= _ISU_i_to_EXU_bits_ctrl_sig_lsu_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_bru_op <= _ISU_i_to_EXU_bits_ctrl_sig_bru_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_csr_op <= _ISU_i_to_EXU_bits_ctrl_sig_csr_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
      EXU_i_from_ISU_bits_r_ctrl_sig_mdu_op <= _ISU_i_to_EXU_bits_ctrl_sig_mdu_op;	// src/main/scala/rv32e/core.scala:40:27, src/main/scala/rv32e/utils/Connect.scala:26:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// <stdin>:3611:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:3611:10
      `FIRRTL_BEFORE_INITIAL	// <stdin>:3611:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:3611:10
      automatic logic [31:0] _RANDOM[0:5];	// <stdin>:3611:10
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:3611:10
        `INIT_RANDOM_PROLOG_	// <stdin>:3611:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:3611:10
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// <stdin>:3611:10
        end	// <stdin>:3611:10
        EXU_i_from_ISU_bits_r_imm = _RANDOM[3'h0];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_pc = _RANDOM[3'h1];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_rdata1 = _RANDOM[3'h2];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_rdata2 = _RANDOM[3'h3];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_rd = _RANDOM[3'h4][4:0];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_reg_wen = _RANDOM[3'h4][5];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_fu_op = _RANDOM[3'h4][8:6];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_mem_wen = _RANDOM[3'h4][9];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_is_ebreak = _RANDOM[3'h4][10];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_not_impl = _RANDOM[3'h4][11];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_src1_op = _RANDOM[3'h4][13:12];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_src2_op = _RANDOM[3'h4][15:14];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_alu_op = _RANDOM[3'h4][19:16];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_lsu_op = _RANDOM[3'h4][23:20];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_bru_op = _RANDOM[3'h4][27:24];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_csr_op = _RANDOM[3'h4][30:28];	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
        EXU_i_from_ISU_bits_r_ctrl_sig_mdu_op = {_RANDOM[3'h4][31], _RANDOM[3'h5][2:0]};	// <stdin>:3611:10, src/main/scala/rv32e/utils/Connect.scala:26:35
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:3611:10
      `FIRRTL_AFTER_INITIAL	// <stdin>:3611:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  IDU IDU_i (	// src/main/scala/rv32e/core.scala:39:27
    .from_IFU_valid                 (_IFU_i_to_IDU_valid),	// src/main/scala/rv32e/core.scala:55:27
    .from_IFU_bits_inst             (_IFU_i_to_IDU_bits_inst),	// src/main/scala/rv32e/core.scala:55:27
    .from_IFU_bits_pc               (_IFU_i_to_IDU_bits_pc),	// src/main/scala/rv32e/core.scala:55:27
    .to_ISU_valid                   (_IDU_i_to_ISU_valid),
    .to_ISU_bits_imm                (_IDU_i_to_ISU_bits_imm),
    .to_ISU_bits_pc                 (_IDU_i_to_ISU_bits_pc),
    .to_ISU_bits_rs1                (_IDU_i_to_ISU_bits_rs1),
    .to_ISU_bits_rs2                (_IDU_i_to_ISU_bits_rs2),
    .to_ISU_bits_rd                 (_IDU_i_to_ISU_bits_rd),
    .to_ISU_bits_ctrl_sig_reg_wen   (_IDU_i_to_ISU_bits_ctrl_sig_reg_wen),
    .to_ISU_bits_ctrl_sig_fu_op     (_IDU_i_to_ISU_bits_ctrl_sig_fu_op),
    .to_ISU_bits_ctrl_sig_mem_wen   (_IDU_i_to_ISU_bits_ctrl_sig_mem_wen),
    .to_ISU_bits_ctrl_sig_is_ebreak (_IDU_i_to_ISU_bits_ctrl_sig_is_ebreak),
    .to_ISU_bits_ctrl_sig_not_impl  (_IDU_i_to_ISU_bits_ctrl_sig_not_impl),
    .to_ISU_bits_ctrl_sig_src1_op   (_IDU_i_to_ISU_bits_ctrl_sig_src1_op),
    .to_ISU_bits_ctrl_sig_src2_op   (_IDU_i_to_ISU_bits_ctrl_sig_src2_op),
    .to_ISU_bits_ctrl_sig_alu_op    (_IDU_i_to_ISU_bits_ctrl_sig_alu_op),
    .to_ISU_bits_ctrl_sig_lsu_op    (_IDU_i_to_ISU_bits_ctrl_sig_lsu_op),
    .to_ISU_bits_ctrl_sig_bru_op    (_IDU_i_to_ISU_bits_ctrl_sig_bru_op),
    .to_ISU_bits_ctrl_sig_csr_op    (_IDU_i_to_ISU_bits_ctrl_sig_csr_op),
    .to_ISU_bits_ctrl_sig_mdu_op    (_IDU_i_to_ISU_bits_ctrl_sig_mdu_op)
  );
  ISU ISU_i (	// src/main/scala/rv32e/core.scala:40:27
    .clock                            (clock),
    .reset                            (reset),
    .from_IDU_valid                   (_IDU_i_to_ISU_valid),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_imm                (_IDU_i_to_ISU_bits_imm),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_pc                 (_IDU_i_to_ISU_bits_pc),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_rs1                (_IDU_i_to_ISU_bits_rs1),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_rs2                (_IDU_i_to_ISU_bits_rs2),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_rd                 (_IDU_i_to_ISU_bits_rd),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_reg_wen   (_IDU_i_to_ISU_bits_ctrl_sig_reg_wen),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_fu_op     (_IDU_i_to_ISU_bits_ctrl_sig_fu_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_mem_wen   (_IDU_i_to_ISU_bits_ctrl_sig_mem_wen),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_is_ebreak (_IDU_i_to_ISU_bits_ctrl_sig_is_ebreak),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_not_impl  (_IDU_i_to_ISU_bits_ctrl_sig_not_impl),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_src1_op   (_IDU_i_to_ISU_bits_ctrl_sig_src1_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_src2_op   (_IDU_i_to_ISU_bits_ctrl_sig_src2_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_alu_op    (_IDU_i_to_ISU_bits_ctrl_sig_alu_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_lsu_op    (_IDU_i_to_ISU_bits_ctrl_sig_lsu_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_bru_op    (_IDU_i_to_ISU_bits_ctrl_sig_bru_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_csr_op    (_IDU_i_to_ISU_bits_ctrl_sig_csr_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_IDU_bits_ctrl_sig_mdu_op    (_IDU_i_to_ISU_bits_ctrl_sig_mdu_op),	// src/main/scala/rv32e/core.scala:39:27
    .from_WBU_bits_reg_wen            (_WBU_i_to_ISU_bits_reg_wen),	// src/main/scala/rv32e/core.scala:42:27
    .from_WBU_bits_wdata              (_WBU_i_to_ISU_bits_wdata),	// src/main/scala/rv32e/core.scala:42:27
    .from_WBU_bits_rd                 (_WBU_i_to_ISU_bits_rd),	// src/main/scala/rv32e/core.scala:42:27
    .to_EXU_valid                     (_ISU_i_to_EXU_valid),
    .to_EXU_bits_imm                  (_ISU_i_to_EXU_bits_imm),
    .to_EXU_bits_pc                   (_ISU_i_to_EXU_bits_pc),
    .to_EXU_bits_rdata1               (_ISU_i_to_EXU_bits_rdata1),
    .to_EXU_bits_rdata2               (_ISU_i_to_EXU_bits_rdata2),
    .to_EXU_bits_rd                   (_ISU_i_to_EXU_bits_rd),
    .to_EXU_bits_ctrl_sig_reg_wen     (_ISU_i_to_EXU_bits_ctrl_sig_reg_wen),
    .to_EXU_bits_ctrl_sig_fu_op       (_ISU_i_to_EXU_bits_ctrl_sig_fu_op),
    .to_EXU_bits_ctrl_sig_mem_wen     (_ISU_i_to_EXU_bits_ctrl_sig_mem_wen),
    .to_EXU_bits_ctrl_sig_is_ebreak   (_ISU_i_to_EXU_bits_ctrl_sig_is_ebreak),
    .to_EXU_bits_ctrl_sig_not_impl    (_ISU_i_to_EXU_bits_ctrl_sig_not_impl),
    .to_EXU_bits_ctrl_sig_src1_op     (_ISU_i_to_EXU_bits_ctrl_sig_src1_op),
    .to_EXU_bits_ctrl_sig_src2_op     (_ISU_i_to_EXU_bits_ctrl_sig_src2_op),
    .to_EXU_bits_ctrl_sig_alu_op      (_ISU_i_to_EXU_bits_ctrl_sig_alu_op),
    .to_EXU_bits_ctrl_sig_lsu_op      (_ISU_i_to_EXU_bits_ctrl_sig_lsu_op),
    .to_EXU_bits_ctrl_sig_bru_op      (_ISU_i_to_EXU_bits_ctrl_sig_bru_op),
    .to_EXU_bits_ctrl_sig_csr_op      (_ISU_i_to_EXU_bits_ctrl_sig_csr_op),
    .to_EXU_bits_ctrl_sig_mdu_op      (_ISU_i_to_EXU_bits_ctrl_sig_mdu_op)
  );
  EXU EXU_i (	// src/main/scala/rv32e/core.scala:41:27
    .clock                            (clock),
    .reset                            (reset),
    .from_ISU_valid                   (_ISU_i_to_EXU_valid),	// src/main/scala/rv32e/core.scala:40:27
    .from_ISU_bits_imm                (EXU_i_from_ISU_bits_r_imm),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_pc                 (EXU_i_from_ISU_bits_r_pc),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_rdata1             (EXU_i_from_ISU_bits_r_rdata1),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_rdata2             (EXU_i_from_ISU_bits_r_rdata2),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_rd                 (EXU_i_from_ISU_bits_r_rd),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_reg_wen   (EXU_i_from_ISU_bits_r_ctrl_sig_reg_wen),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_fu_op     (EXU_i_from_ISU_bits_r_ctrl_sig_fu_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_mem_wen   (EXU_i_from_ISU_bits_r_ctrl_sig_mem_wen),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_is_ebreak (EXU_i_from_ISU_bits_r_ctrl_sig_is_ebreak),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_not_impl  (EXU_i_from_ISU_bits_r_ctrl_sig_not_impl),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_src1_op   (EXU_i_from_ISU_bits_r_ctrl_sig_src1_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_src2_op   (EXU_i_from_ISU_bits_r_ctrl_sig_src2_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_alu_op    (EXU_i_from_ISU_bits_r_ctrl_sig_alu_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_lsu_op    (EXU_i_from_ISU_bits_r_ctrl_sig_lsu_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_bru_op    (EXU_i_from_ISU_bits_r_ctrl_sig_bru_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_csr_op    (EXU_i_from_ISU_bits_r_ctrl_sig_csr_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .from_ISU_bits_ctrl_sig_mdu_op    (EXU_i_from_ISU_bits_r_ctrl_sig_mdu_op),	// src/main/scala/rv32e/utils/Connect.scala:26:35
    .lsu_to_cache_ready               (_dcache_from_LSU_ready),	// src/main/scala/rv32e/core.scala:67:27
    .lsu_from_cache_valid             (_dcache_to_LSU_valid),	// src/main/scala/rv32e/core.scala:67:27
    .lsu_from_cache_bits_data         (_dcache_to_LSU_bits_data),	// src/main/scala/rv32e/core.scala:67:27
    .lsu_from_cache_bits_bresp        (_dcache_to_LSU_bits_bresp),	// src/main/scala/rv32e/core.scala:67:27
    .from_ISU_ready                   (_EXU_i_from_ISU_ready),
    .to_WBU_valid                     (_EXU_i_to_WBU_valid),
    .to_WBU_bits_alu_result           (_EXU_i_to_WBU_bits_alu_result),
    .to_WBU_bits_mdu_result           (_EXU_i_to_WBU_bits_mdu_result),
    .to_WBU_bits_lsu_rdata            (_EXU_i_to_WBU_bits_lsu_rdata),
    .to_WBU_bits_csr_rdata            (_EXU_i_to_WBU_bits_csr_rdata),
    .to_WBU_bits_pc                   (_EXU_i_to_WBU_bits_pc),
    .to_WBU_bits_reg_wen              (_EXU_i_to_WBU_bits_reg_wen),
    .to_WBU_bits_rd                   (_EXU_i_to_WBU_bits_rd),
    .to_WBU_bits_fu_op                (_EXU_i_to_WBU_bits_fu_op),
    .to_IFU_bits_bru_ctrl_br          (_EXU_i_to_IFU_bits_bru_ctrl_br),
    .to_IFU_bits_bru_addr             (_EXU_i_to_IFU_bits_bru_addr),
    .to_IFU_bits_csr_ctrl_br          (_EXU_i_to_IFU_bits_csr_ctrl_br),
    .to_IFU_bits_csr_addr             (_EXU_i_to_IFU_bits_csr_addr),
    .difftest_mcause                  (io_out_difftest_mcause),
    .difftest_mepc                    (io_out_difftest_mepc),
    .difftest_mstatus                 (io_out_difftest_mstatus),
    .difftest_mtvec                   (io_out_difftest_mtvec),
    .lsu_to_cache_valid               (_EXU_i_lsu_to_cache_valid),
    .lsu_to_cache_bits_addr           (_EXU_i_lsu_to_cache_bits_addr),
    .lsu_to_cache_bits_wdata          (_EXU_i_lsu_to_cache_bits_wdata),
    .lsu_to_cache_bits_is_write       (_EXU_i_lsu_to_cache_bits_is_write),
    .lsu_to_cache_bits_wmask          (_EXU_i_lsu_to_cache_bits_wmask)
  );
  WBU WBU_i (	// src/main/scala/rv32e/core.scala:42:27
    .from_EXU_valid           (_EXU_i_to_WBU_valid),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_alu_result (_EXU_i_to_WBU_bits_alu_result),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_mdu_result (_EXU_i_to_WBU_bits_mdu_result),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_lsu_rdata  (_EXU_i_to_WBU_bits_lsu_rdata),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_csr_rdata  (_EXU_i_to_WBU_bits_csr_rdata),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_pc         (_EXU_i_to_WBU_bits_pc),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_reg_wen    (_EXU_i_to_WBU_bits_reg_wen),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_rd         (_EXU_i_to_WBU_bits_rd),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_fu_op      (_EXU_i_to_WBU_bits_fu_op),	// src/main/scala/rv32e/core.scala:41:27
    .to_ISU_bits_reg_wen      (_WBU_i_to_ISU_bits_reg_wen),
    .to_ISU_bits_wdata        (_WBU_i_to_ISU_bits_wdata),
    .to_ISU_bits_rd           (_WBU_i_to_ISU_bits_rd),
    .to_IFU_valid             (_WBU_i_to_IFU_valid)
  );
  IFU_cache IFU_i (	// src/main/scala/rv32e/core.scala:55:27
    .clock                     (clock),
    .reset                     (reset),
    .from_EXU_bits_bru_ctrl_br (_EXU_i_to_IFU_bits_bru_ctrl_br),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_bru_addr    (_EXU_i_to_IFU_bits_bru_addr),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_csr_ctrl_br (_EXU_i_to_IFU_bits_csr_ctrl_br),	// src/main/scala/rv32e/core.scala:41:27
    .from_EXU_bits_csr_addr    (_EXU_i_to_IFU_bits_csr_addr),	// src/main/scala/rv32e/core.scala:41:27
    .from_WBU_valid            (_WBU_i_to_IFU_valid),	// src/main/scala/rv32e/core.scala:42:27
    .to_cache_ready            (_icache_from_IFU_ready),	// src/main/scala/rv32e/core.scala:56:27
    .from_cache_valid          (_icache_to_IFU_valid),	// src/main/scala/rv32e/core.scala:56:27
    .from_cache_bits_data      (_icache_to_IFU_bits_data),	// src/main/scala/rv32e/core.scala:56:27
    .to_IDU_valid              (_IFU_i_to_IDU_valid),
    .to_IDU_bits_inst          (_IFU_i_to_IDU_bits_inst),
    .to_IDU_bits_pc            (_IFU_i_to_IDU_bits_pc),
    .to_cache_valid            (_IFU_i_to_cache_valid),
    .to_cache_bits_addr        (_IFU_i_to_cache_bits_addr)
  );
  iCacheV2 icache (	// src/main/scala/rv32e/core.scala:56:27
    .clock                (clock),
    .reset                (reset),
    .from_IFU_valid       (_IFU_i_to_cache_valid),	// src/main/scala/rv32e/core.scala:55:27
    .from_IFU_bits_addr   (_IFU_i_to_cache_bits_addr),	// src/main/scala/rv32e/core.scala:55:27
    .to_sram_ar_ready     (_sram_i_axi_ar_ready),	// src/main/scala/rv32e/core.scala:57:27
    .to_sram_r_valid      (_sram_i_axi_r_valid),	// src/main/scala/rv32e/core.scala:57:27
    .to_sram_r_bits_data  (_sram_i_axi_r_bits_data),	// src/main/scala/rv32e/core.scala:57:27
    .to_sram_r_bits_last  (_sram_i_axi_r_bits_last),	// src/main/scala/rv32e/core.scala:57:27
    .from_IFU_ready       (_icache_from_IFU_ready),
    .to_IFU_valid         (_icache_to_IFU_valid),
    .to_IFU_bits_data     (_icache_to_IFU_bits_data),
    .to_sram_ar_valid     (_icache_to_sram_ar_valid),
    .to_sram_ar_bits_addr (_icache_to_sram_ar_bits_addr),
    .to_sram_ar_bits_len  (_icache_to_sram_ar_bits_len),
    .to_sram_r_ready      (_icache_to_sram_r_ready)
  );
  sram_axi_rw sram_i (	// src/main/scala/rv32e/core.scala:57:27
    .clock             (clock),
    .reset             (reset),
    .axi_ar_valid      (_icache_to_sram_ar_valid),	// src/main/scala/rv32e/core.scala:56:27
    .axi_ar_bits_addr  (_icache_to_sram_ar_bits_addr),	// src/main/scala/rv32e/core.scala:56:27
    .axi_ar_bits_len   (_icache_to_sram_ar_bits_len),	// src/main/scala/rv32e/core.scala:56:27
    .axi_r_ready       (_icache_to_sram_r_ready),	// src/main/scala/rv32e/core.scala:56:27
    .axi_aw_valid      (1'h0),	// src/main/scala/rv32e/core.scala:68:27
    .axi_aw_bits_addr  (32'h0),	// src/main/scala/rv32e/core.scala:57:27
    .axi_aw_bits_len   (8'h0),	// src/main/scala/rv32e/core.scala:57:27
    .axi_aw_bits_burst (2'h0),	// src/main/scala/rv32e/core.scala:57:27
    .axi_w_valid       (1'h0),	// src/main/scala/rv32e/core.scala:68:27
    .axi_w_bits_data   (32'h0),	// src/main/scala/rv32e/core.scala:57:27
    .axi_w_bits_strb   (4'h0),	// src/main/scala/rv32e/core.scala:57:27
    .axi_ar_ready      (_sram_i_axi_ar_ready),
    .axi_r_valid       (_sram_i_axi_r_valid),
    .axi_r_bits_data   (_sram_i_axi_r_bits_data),
    .axi_r_bits_last   (_sram_i_axi_r_bits_last),
    .axi_aw_ready      (/* unused */),
    .axi_w_ready       (/* unused */)
  );
  D_Cache dcache (	// src/main/scala/rv32e/core.scala:67:27
    .clock                  (clock),
    .reset                  (reset),
    .from_LSU_valid         (_EXU_i_lsu_to_cache_valid),	// src/main/scala/rv32e/core.scala:41:27
    .from_LSU_bits_addr     (_EXU_i_lsu_to_cache_bits_addr),	// src/main/scala/rv32e/core.scala:41:27
    .from_LSU_bits_wdata    (_EXU_i_lsu_to_cache_bits_wdata),	// src/main/scala/rv32e/core.scala:41:27
    .from_LSU_bits_is_write (_EXU_i_lsu_to_cache_bits_is_write),	// src/main/scala/rv32e/core.scala:41:27
    .from_LSU_bits_wmask    (_EXU_i_lsu_to_cache_bits_wmask),	// src/main/scala/rv32e/core.scala:41:27
    .to_sram_ar_ready       (_sram_i2_axi_ar_ready),	// src/main/scala/rv32e/core.scala:68:27
    .to_sram_r_valid        (_sram_i2_axi_r_valid),	// src/main/scala/rv32e/core.scala:68:27
    .to_sram_r_bits_data    (_sram_i2_axi_r_bits_data),	// src/main/scala/rv32e/core.scala:68:27
    .to_sram_r_bits_last    (_sram_i2_axi_r_bits_last),	// src/main/scala/rv32e/core.scala:68:27
    .to_sram_aw_ready       (_sram_i2_axi_aw_ready),	// src/main/scala/rv32e/core.scala:68:27
    .to_sram_w_ready        (_sram_i2_axi_w_ready),	// src/main/scala/rv32e/core.scala:68:27
    .from_LSU_ready         (_dcache_from_LSU_ready),
    .to_LSU_valid           (_dcache_to_LSU_valid),
    .to_LSU_bits_data       (_dcache_to_LSU_bits_data),
    .to_LSU_bits_bresp      (_dcache_to_LSU_bits_bresp),
    .to_sram_ar_valid       (_dcache_to_sram_ar_valid),
    .to_sram_ar_bits_addr   (_dcache_to_sram_ar_bits_addr),
    .to_sram_ar_bits_len    (_dcache_to_sram_ar_bits_len),
    .to_sram_r_ready        (_dcache_to_sram_r_ready),
    .to_sram_aw_valid       (_dcache_to_sram_aw_valid),
    .to_sram_aw_bits_addr   (_dcache_to_sram_aw_bits_addr),
    .to_sram_aw_bits_len    (_dcache_to_sram_aw_bits_len),
    .to_sram_w_valid        (_dcache_to_sram_w_valid),
    .to_sram_w_bits_data    (_dcache_to_sram_w_bits_data)
  );
  sram_axi_rw sram_i2 (	// src/main/scala/rv32e/core.scala:68:27
    .clock             (clock),
    .reset             (reset),
    .axi_ar_valid      (_dcache_to_sram_ar_valid),	// src/main/scala/rv32e/core.scala:67:27
    .axi_ar_bits_addr  (_dcache_to_sram_ar_bits_addr),	// src/main/scala/rv32e/core.scala:67:27
    .axi_ar_bits_len   (_dcache_to_sram_ar_bits_len),	// src/main/scala/rv32e/core.scala:67:27
    .axi_r_ready       (_dcache_to_sram_r_ready),	// src/main/scala/rv32e/core.scala:67:27
    .axi_aw_valid      (_dcache_to_sram_aw_valid),	// src/main/scala/rv32e/core.scala:67:27
    .axi_aw_bits_addr  (_dcache_to_sram_aw_bits_addr),	// src/main/scala/rv32e/core.scala:67:27
    .axi_aw_bits_len   (_dcache_to_sram_aw_bits_len),	// src/main/scala/rv32e/core.scala:67:27
    .axi_aw_bits_burst (2'h1),	// src/main/scala/rv32e/core.scala:68:27
    .axi_w_valid       (_dcache_to_sram_w_valid),	// src/main/scala/rv32e/core.scala:67:27
    .axi_w_bits_data   (_dcache_to_sram_w_bits_data),	// src/main/scala/rv32e/core.scala:67:27
    .axi_w_bits_strb   (4'hF),	// src/main/scala/rv32e/core.scala:68:27
    .axi_ar_ready      (_sram_i2_axi_ar_ready),
    .axi_r_valid       (_sram_i2_axi_r_valid),
    .axi_r_bits_data   (_sram_i2_axi_r_bits_data),
    .axi_r_bits_last   (_sram_i2_axi_r_bits_last),
    .axi_aw_ready      (_sram_i2_axi_aw_ready),
    .axi_w_ready       (_sram_i2_axi_w_ready)
  );
  assign io_out_inst = _IFU_i_to_IDU_bits_inst;	// <stdin>:3611:10, src/main/scala/rv32e/core.scala:55:27
  assign io_out_pc = _IFU_i_to_IDU_bits_pc;	// <stdin>:3611:10, src/main/scala/rv32e/core.scala:55:27
  assign io_out_wb = _WBU_i_to_IFU_valid;	// <stdin>:3611:10, src/main/scala/rv32e/core.scala:42:27
endmodule

